### ISSUE TITLE
LYWSD02 HA 0.113.2 stop update sensor states after some times

### ISSUE THREAD

**Issue by shirou93** [custom-components/sensor.mitemp_bt#102]
LYWSD02  stop update states on 0.6.10. When sensor stop update states i can connect via mihome app and this will solve problem for some time.

HASSOS RPI4

**Comment by Ernst79** [comment]
Did you check the faq? Perpaps connection issues? Do you get errors in your log? Try to enable debug logging, to see if the component fails, or it is just not receiving messages anymore. 

You need to provide more info to help you.

**Comment by shirou93** [comment]
No errors in log when i enable debug. Strange because when i connect via mihome instantly states update on HA.

**Comment by shirou93** [comment]
I reinstall hassos and work like charm.
