### ISSUE TITLE
Any of the supported sensors suitable for outdoors?

### ISSUE THREAD

**Issue by hugalafutro** [custom-components/sensor.mitemp_bt#103]
Hi, not an issue, but dunno where else to ask. I have several LYWSD03MMC around the house and wanted to have a sensor for temp/humidity outside the window. Was considering just putting another LYWSD03MMC outside and put it in a plastic baggie, but there's condensation to think about and also I do not think it's rated for under zero temperatures.

So I was wondering if any of the sensors this integration supports is suitable for outdoor use?

**Comment by Ernst79** [comment]
I use the MiFlora (HHCCJCY01) outdoors. I’ve seen others who said that they have used the all year long outside. According to the specs on amazon it also can be used Indoors and Outdoors (IPX5 Waterproof). The Vetrug (GCLS002 ) is the same device

https://www.amazon.com/HHCC-Xiaomi-Plant-Flower-Monitor/dp/B06X9V2FKJ
