### ISSUE TITLE
Does it support ESP32?

### ISSUE THREAD

**Issue by Fifar4** [custom-components/sensor.mitemp_bt#104]
I read the guide and it is excellent.
But how do I add ESP32 as a BLE hub?

**Comment by Ernst79** [comment]
This component is not working with an ESP32, but is using the bluetooth radio from your device that is running Home Assistant (raspberry/PC/NUC/...). ESP32 cannot run Home Assistant. 

The easiest solution you are looking for is ESPhome. 

It supports [LYSDCGQ](https://esphome.io/components/sensor/xiaomi_lywsdcgq.html), [CGG1](https://esphome.io/components/sensor/xiaomi_cgg1.html), [HHCCJCY01 ](https://esphome.io/components/sensor/xiaomi_hhccjcy01.html)and [LYWSD02](https://esphome.io/components/sensor/xiaomi_lywsd02.html)

ESPHome is aimed at ESP32 devices and is supported very well by home assistant,  

Closing this issue now, as ESPHome/ESP32 is outside the scope of this component.
