### ISSUE TITLE
Is it possible to name the sensors through config?

### ISSUE THREAD

**Issue by thomasvs** [custom-components/sensor.mitemp_bt#105]
The included component allows naming each sensor in the config.  It seems like this custom component doesn' t make that possible, and since (for my vegtrug sensors) it exposes 4-5 sensors, I have to rename each sensor 5 times in homeassistant.  Is there any alternative for that?

**Comment by Ernst79** [comment]
I will look into this. I will follow the approach as suggested by @clau-bucur in #3. 

> One approach could be that instead of generating entities in the format "sensor.mi_t/h/batt_MAC" they will be generated as "sensor.mi_t/h/batt_CUSTOM_NAME".

Please allow me some time, to figure this out.

**Comment by Ernst79** [comment]
Hi, I've made a lot of progress and it is working already on my local system. But I have a question to you all. As you can see, each sensor has an entity_id and a Name Override. In the example below I used 'derde naam' as custom name (derde naam is third name in Dutch for those who want to know). 

![image](https://user-images.githubusercontent.com/24375847/95381753-e1489f80-08e8-11eb-986a-ee22638f3644.png)

**question 1**
In the old situation, Name Override was 'mi t_AA:BB:CC:11:22:33'. I want to make this default to 'Temperature CUSTOM NAME'. If no custom name is given, it will be 'Temperature AABBCC112233' Do you agree? This name can always be overwritten in the UI, but I think Temperature will be a better default name compared to "mi t_"

**question 2**
The entity_id is now using the custom name with a prefix of 'mi_t_CUSTOM_NAME' (if you don't give an custom name, it will use the mac address). However, this name has to be unique, which is where my concern is. A mac address will be unique, normally, but a custom name perhaps not. I know it has mi_t_ as prefix, which makes is a bit better, but you can easily define the same name (e.g. a room) for different mitemp sensors now.  I'll have to think about this, but perhaps one of you have an idea. Or is it ok to use the mac address for the enity_id?

**Comment by clau-bucur** [comment]
Hi!

1. I agree with this. Maybe you can extend the same logic also for the generated Humidity and Battery sensors.

2. The entity ID collision can happen for any HA integration that allows to define your custom entity IDs, so I don't think this should be a concern, IMHO. It can be viewed as a misconfiguration on the user side, which could be easily identified and rectified.
> 
> Or is it ok to use the mac address for the enity_id?

That very thing was our suggestion, that we optionally get rid of the mac address for the entity_id with this new configuration option.

**Comment by Ernst79** [comment]
Thank for the feedback.

1. Yes, of course, I’ve done that for all sensor types, also the exotic ones, like formaldehyde. Temperature was just as example. See the custom_names branch.

2. Ok, Perhaps I can add a check that at least in the config of mitemp different names are used. I’ll look into that ASAP and will make a beta release.

**Comment by Ernst79** [comment]
Note to myself. 

Made some further progress. The sensor name and enity_id both turn out to be generated based on the "name" property, not the "unique_id", see this [page](https://developers.home-assistant.io/docs/core/entity#generic-properties). So my initial idea of having a name "Temperature Livingroom" and a entity_id "sensor.mi_t_livingroom" is not going to work. It will be generated as "sensor.temperature_livingroom". Not bad, but the risk of getting the same name twice will be bigger. 

Next step, figuring out what happens if I use the same name as an entity that is already there.

**Comment by Ernst79** [comment]
Note to myself.

I see two solutions, when using a custom sensor name, 
1. it changes the unique_id, which will result in the old sensor to become unavailable and a new sensor being created (with a new entity_id). This means that users have to change their lovelace cards to use the new entity_id manually. History will be lost. Old sensors have to be deleted manually. 
2. it changes the entity_id, not the unique_id. History will be kept. I think (not sure) this will automatically update the lovelace cards to use the new entity_id. There are no old sensors left over that have to be deleted. 

So, I prefer the 2nd option.
The entity_id is stored in 'state.entity_id' in the format 'domain.object_id', so, we need to change 'state.object_id' when the name is changed in the config. 
Next step: figuring out how to do this.....

**Comment by Ernst79** [comment]
It is not as easy as I hoped, I tried the first option, but unfortunately, that doesn't play nicely with the entity_id. I now have the issue that if someone tries to change the name in the UI, it complains that the entity doesn't have a unique_id anymore. Still working on it, but it will take a while.

**Comment by clau-bucur** [comment]
Thank you!

**Comment by Ernst79** [comment]
So, finally, I've managed to get it working. Unfortunately, it will create new entities, so you will have to update your lovelace cards, automations and/or scripts, when using the new `sensor_names` option. I made it such that users who do not use the `sensor_names` option, won't have to change anything and will keep the old name. @clau-bucur and @thomasvs I hope you can check if it works for you. Please install the beta 0.7.2 to try out, by enabling beta releases in HACS.

**Comment by clau-bucur** [comment]
Nice work @Ernst79!
I've installed 0.7.2 earlier. Everything looks really good up to now:
![image](https://user-images.githubusercontent.com/47672949/96098618-ffab2e00-0eda-11eb-8cea-3630b1119f99.png)

**Comment by Ernst79** [comment]
Thanks for the feedback, lets keep an eye on it for a couple of days. This weekend, I will release it as final version if nothing happens. Hopefully @thomasvs can also try it out.

**Comment by Ernst79** [comment]
0.7.2 is released, which adds support of names through config.
