### ISSUE TITLE
It would be nice if this can also be installed in RPi 0 Ws

### ISSUE THREAD

**Issue by circa1741** [custom-components/sensor.mitemp_bt#109]
I currently have "sensor.mitemp_bt" installed via HACS in a laptop with HA. Unfortunately, the laptop is not centrally located.

I use "room-assistant" (for room-level presence detection) which can be installed as an add-on and separately in RPi 0 Ws.
see https://www.room-assistant.io/guide/installation.html#running-with-home-assistant-os and https://www.room-assistant.io/guide/quickstart-pi-zero-w.html#requirements.

I have several RPi 0 Ws spread around the house. It would be nice if "sensor.mitemp_bt" can also be installed in RPi 0 Ws and configured to listened to specific mitemp devices. For example, I have mitemp devices in the master room and the master bath. I can then configure the RPi 0 W in the master room to listen to the mitemp devices in the master room and master bath. I can then configure the RPi 0 W in the guest room to listen to the mitemp devices in the guest room and guest bath. etc.

**Comment by ACrazyConcept** [comment]
You could run Home Assistant on the Zero's. I do that on a couple and then collect their data on my main HA.

**Comment by Ernst79** [comment]
In addition to the answer of @ACrazyConcept , you can whitelist sensors on each of your pi zero’s, to prevent sensors being detected twice.

```
sensor:
  - platform: mitemp_bt
    whitelist:
      - '58:C1:38:2F:86:6C'
      - 'C4:FA:64:D1:61:7D'
```
