### ISSUE TITLE
All sensors not found after restart

### ISSUE THREAD

**Issue by frasskungin** [custom-components/sensor.mitemp_bt#11]
I previously had one Xiaomi sensor and used this component to integrate, and it worked like a charm. Today I received two more sensors and home assistant were able to find them right after I pressed the pairing button on the sensor. But now when I restart hass.io, only two of the three sensors are created as entities. The third one is found when I manually press the pairing button on the sensor.

Is there any way to overcome this without having to manually press the pairing button on the sensor after a restart?

**Comment by frasskungin** [comment]
I was a bit too quick to report an issue it seems, there was just quite long delay before the third sensor was automatically found...

**Comment by Magalex2x14** [comment]
Minimum time, required to pick up sensors after HA restart, is equal to period option (60s by default). In case of unstable packets receiving (long distance, for example) it can be longer, if during first period no packets was received...
