### ISSUE TITLE
LYWSD03MMC Error: does not match regular expression

### ISSUE THREAD

**Issue by raahib** [custom-components/sensor.mitemp_bt#114]
Invalid config for [sensor.mitemp_bt]: value F09D59781AFFF5BF2000839B does not match regular expression (?i)^[A-F0-9]{32}$ for dictionary value @ data['encryptors']['a4:c1:38:ce:2a:67']. Got 'F09D59781AFFF5BF2000839B'. (See /config/configuration.yaml, line 33). Please check the docs at https://github.com/custom-components/sensor.mitemp_bt

The LYWSD03MMC has with firmware 1.0.0_0109 a 24 digit token. 

...
        "mac" : "A4:C1:38:CE:2A:67",
        "localip" : "92.200.183.69",
        "show_mode" : 1,
        "longitude" : "0.00000000",
        "latitude" : "0.00000000",
        "isOnline" : false,
        "token" : "F09D59781AFFF5BF2000839B",
        "bssid" : "",
        "did" : "blt.4.13t75k8l4gk00",
        "pid" : 6,
        "model" : "miaomiaoce.sensor_ht.t2",
...

**Comment by omerbitas** [comment]
Got the exact same error. the cause is a token of 24 digits instead of 32, FW version 1.0.0_0001, model is miaomiaoce.sensor_ht.t2 (LYWSD03MMC). any solution for this? extracted using the hacked mi home version (veve).

**Comment by raahib** [comment]
I found now this Project : https://github.com/mKeRix/room-assistant/issues/277. It extract the Mi Token (24 char) and Bind Key (32 char). I used the **Bind Key** in HA and it works, insane.

**Comment by Ernst79** [comment]
You need the 32 char key. I’ve added the instructions to the faq, as given in your link. Thanks.
