### ISSUE TITLE
GCLS002 picture in the readme is wrong

### ISSUE THREAD

**Issue by ACrazyConcept** [custom-components/sensor.mitemp_bt#120]
Just FYI the picture for GCLS002 in the readme is wrong. This is the VegTrug Grow Care Garden / GCLS002:

![image](https://user-images.githubusercontent.com/36438756/95078136-efde5d80-0714-11eb-8ee0-424308ffce3f.png)

**Comment by Ernst79** [comment]
Thanks, I've updated the pictures in the faq (after removing the USB cable).
