### ISSUE TITLE
lost connection after update to HassOs 4.14

### ISSUE THREAD

**Issue by mohannadalsharief** [custom-components/sensor.mitemp_bt#123]
running on RPI 3 and got an update to HassOS 4.14 where all my connections are gone

**Comment by Ernst79** [comment]
Please enable debug logging and show your logs. Did you restart your RPI3 after the update?

**Comment by mohannadalsharief** [comment]
yes multiple times

Logger: custom_components.mitemp_bt.sensor
Source: custom_components/mitemp_bt/sensor.py:131
Integration: mitemp_bt (documentation)
First occurred: 9:10:59 PM (10 occurrences)
Last logged: 9:20:01 PM

HCIdump thread: OS error: [Errno 19] error while attempting to bind on interface 0: No such device

**Comment by Ernst79** [comment]
could you run the following command in SSH, and give the result

`hcitool dev`

**Comment by mohannadalsharief** [comment]
it says command not found, am i missing sth?

**Comment by Ernst79** [comment]
I think that due to the HassOs update, some bluetooth things are missing.

**Comment by mohannadalsharief** [comment]
do you know how I can roll ack or what shall I do

**Comment by Ernst79** [comment]
I see some others on the forum have rolled back to 4.13, but I don't have HassOs. But I think it is better if we solve this. It looks like you don't have hcitools. Did you try `sudo apt-get install pi-bluetooth` ? (perhaps without sudo on HassOs)

**Comment by mohannadalsharief** [comment]
sudo command not foun, not sure what is happening

**Comment by Ernst79** [comment]
Try without sudo.

I though HassOs is not allowing root access

**Comment by Ernst79** [comment]
Also try to run this command again, as you would have to do with a new installation, according to the instructions.
```
setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which python3\``
```

**Comment by Ernst79** [comment]
One of the people on the [forum](https://community.home-assistant.io/t/xiaomi-passive-ble-monitor-sensor-platform/177352/457?u=ernst) have fixed it by removing the custom component, configuring the built in component, wait till that one starts receiving hci events, and then, install the custom component again.

**Comment by mohannadalsharief** [comment]
Thanks for the help, is there clear steps to configure the built in component?

**Comment by Ernst79** [comment]
I assume that you have tried the first suggestions and they didn’t work?

Instructions are [here.](https://www.home-assistant.io/integrations/mitemp_bt/)

**Comment by mohannadalsharief** [comment]
Now I am stuck waiting blutoothhd to connect ... I guess I will just roll back

**Comment by Ernst79** [comment]
On which command are you stuck? Does hcitool lescan work?

**Comment by mohannadalsharief** [comment]
no it doesnt and using the built in component didnt work as well

**Comment by Ernst79** [comment]
I see an [issue](https://github.com/home-assistant/operating-system/issues/910) has been reported on HassOs repo as well. For now, I think it is better to roll back. 

#https://github.com/home-assistant/operating-system/issues/910

**Comment by maximcoder** [comment]
> I see an [issue](https://github.com/home-assistant/operating-system/issues/910) has been reported on HassOs repo as well. For now, I think it is better to roll back.
> 
> #[home-assistant/operating-system#910](https://github.com/home-assistant/operating-system/issues/910)

whats the quick way to roll back to 4.13 ?

**Comment by Ernst79** [comment]
`ha os update --version 4.13`

There seems to be an issue with HassOs 4.14 with Bluetooth, as both the build in component as well as the Bluetooth tracker do not work anymore after upgrading.

**Comment by phoxy84** [comment]
Going back to 4.13 works.

**Comment by Ernst79** [comment]
HassOs 4.15 is released, which should solve the issue.

**Comment by phoxy84** [comment]
Installed 4.15 and can confirm that it works.
