### ISSUE TITLE
Don't work after upgrade to 0.7.4-beta

### ISSUE THREAD

**Issue by valsergi** [custom-components/sensor.mitemp_bt#127]
Hello, I have updated to the latest BETA version and the integration has stopped working right now, none of the sensors shows me data, I have a LYWSD03MMC and so far everything is OK, I have downloaded the version and it has worked correctly again .

![image](https://user-images.githubusercontent.com/64151129/96636682-edd3eb80-131d-11eb-833e-087e7ee7aac9.png)
![image](https://user-images.githubusercontent.com/64151129/96636765-0cd27d80-131e-11eb-8c11-65e03831d392.png)

Thank you for your work!

**Comment by Ernst79** [comment]
Thanks for reporting. That is really strange, it works fine on my end. I will revert this import, and look into this.

**Comment by Ernst79** [comment]
Aha, found it. This LIGHT_LUX component is introduced in 0.116. So it will work fine after updating to core 0.116

**Comment by valsergi** [comment]
Yes, I am still on version 0.115.6 as you can see in my screenshot, for now I will not upload because there are more devices that cause me problems and my knowledge does not allow me to fix it. thanks for the answers

**Comment by Ernst79** [comment]
I've reverted the LIGHT_LUX import. I've decided to wait a little while before making this change, to make sure that most users are on 0.116. So it should be safe for you to update to 0.7.4 when it becomes stable.

**Comment by Ernst79** [comment]
0.7.4 final is released today, which fixes this issue. Note that this change will be made later when HA core 0.118 is released.
