### ISSUE TITLE
typo in sensor.py

### ISSUE THREAD

**Issue by MarpleA** [custom-components/sensor.mitemp_bt#128]
Hi,

there is a typo in line 659 of sensor.py
sensors.insert(f_i, FormaldehydeSensor(confing, mac))

should be config instead of confing

Best

**Comment by Ernst79** [comment]
Thanks. Will fix it right away in 0.7.5

**Comment by Ernst79** [comment]
0.7.5 is released, which will fix this issue. Thanks again for reporting.
