### ISSUE TITLE
Configuration check reports issue for const: PERCENTAGE and class BinarySensoryEntity - on Home Assistant 0.109.6

### ISSUE THREAD

**Issue by JoedowJoedow** [custom-components/sensor.mitemp_bt#130]
Hey *,

Seems that recently the naming was changed for both used:

PERCENTAGE => now UNIT_PERCENTAGE (homeassistant.const)
BinarySensorEntity => BinarySensorDevice (homeassistant\lib\python3.7\site-packages\homeassistant\components\binary_sensor)

This causes the configuration check in HomeAssistant to report an problem.
I am not quite sure about my findings, but when exchanging it to the proposed ones, the error is gone.

By the way thanks for your work/effort.

Kind regards

**Comment by Ernst79** [comment]
This has been changed in HA 0.115, see  https://github.com/home-assistant/core/pull/39383
The prefix UNIT_ had been removed in 0.115.

Please update to HA 0.115 or later or stick to mitemp_bt 0.7.3.

**Comment by JoedowJoedow** [comment]
Thanks for the quick reply and sorry for the inconvenience. Greets
