### ISSUE TITLE
LYWSD03MMC

### ISSUE THREAD

**Issue by Blak-DK** [custom-components/sensor.mitemp_bt#134]
No battery shown with LYWSD03MMC orig. firmware

**Comment by Ernst79** [comment]
Battery level is reported about once in an hour, so it could take a while before it shows up. How long did you wait?

**Comment by Blak-DK** [comment]
a hole day and just tryed again for 3 houers still no battery have to go back to 7.3

**Comment by Ernst79** [comment]
Just to be sure, it is only working on 7.3?, not on 7.4 and above?

**Comment by Blak-DK** [comment]
Yes correct only 7.3 works i will tjek and return to you :-)

**Comment by Blak-DK** [comment]
Solved it was as you wrote the just changed names Thanks :-)

**Comment by Ernst79** [comment]
Thanks for reporting back. Unfortunately this can happen sometimes. 0.7.4 changed names for new sensors, old ones should have kept the same. But sometimes this apparently goes wrong and your sensor will get the new name. Glad it is solved!
