### ISSUE TITLE
Move communication to BLE devices to pypi package

### ISSUE THREAD

**Issue by Ernst79** [custom-components/sensor.mitemp_bt#14]
This custom component will (hopefully) result in an official integration in Home Assistant. First, a couple of bugs need to be fixed, which will take some time. 

When that is finished, the next step would be to create a pypi package that handles the communication part of the code. The official home assistant developers documentation states the following:

> All communication to external devices or services must be wrapped in an external Python library hosted on pypi.

This issue is created to collect the information we need, and to discuss the development for this. 

**Note however that @Magalex2x14 is first focusing on bug fixing the current code.** 

- Instructions to create pypi packages
https://packaging.python.org/tutorials/packaging-projects/

**Progress**
- [x] Created and uploaded an example package at the [test environment](https://test.pypi.org/project/example-pkg-Ernst79/0.0.1/) of pypi.

**Comment by Ernst79** [comment]
@Magalex2x14 This issue is not aimed to push you. I just created this issue for myself, so I can start looking into this, collect information and prepare some stuff. Even if it takes months before all bugs are sorted out, I can already start looking into this what we need in the end. I guess, in the end, we can just move part of your code out of sensor.py to the pypi package.

**Comment by Magalex2x14** [comment]
This issue intersects with #9 . It is quite possible that the matter will be solved with the help of existing libraries using the BlueZ D-Bus API.

**Comment by Ernst79** [comment]
Ok, it’s not quite clear to me when one should move things to an pypi package and when not. Let’s see after you’ve implemented #9 if this issue is still relevant. Found an example here, maybe helpful for you. https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/test/example-gatt-client

**Comment by Ernst79** [comment]
Closing this issue for now. We can always reopen it if needed.
