### ISSUE TITLE
Not possible to get battery level from Xiaomi Mosquito Repellent Smart

### ISSUE THREAD

**Issue by pilot1981** [custom-components/sensor.mitemp_bt#143]
Hi,
I'm trying to get battery level from Xiaomi Mosquito Repellent; I tried this config but I obtain errors...

  - platform: mitemp_bt
    mac: '74-a3-4a-c0-xx-xx'
    name: Mosquito
    monitored_conditions:
      - battery

**Comment by Ernst79** [comment]
Are you using the built-in component or this custom component? For the last, you config should be:

sensor:
  - platform: mitemp_bt
    batt_entities: True
    whitelist:
      - 'C4:7C:8D:6B:4F:F3'

**Comment by pilot1981** [comment]
Yes, I use integrated version but using your example I obtain this error:

Invalid config for [sensor.mitemp_bt]: value 74-a3-4a-c0-16-xx does not match regular expression (?i)^(?:[0-9A-F]{2}[:]){5}(?:[0-9A-F]{2})$ @ data['whitelist'][0]. Got '74-a3-4a-c0-16-xx’. (See ?, line ?).

**Comment by Ernst79** [comment]
you have to use `:` , not `-` in the mac address.

**Comment by pilot1981** [comment]
You are right: it’s only a problem of conversion...

It’s worked fine for me: thanks

It’s also possibile have use level of repellent material?

**Comment by Ernst79** [comment]
Please make a new issue for that, to keep issues clear.
