### ISSUE TITLE
howto get tablet consumption of Xiaomi Mosquito repellent smart

### ISSUE THREAD

**Issue by pilot1981** [custom-components/sensor.mitemp_bt#144]
Hi,
I would get tablet consumption of Xiaomi Mosquito repellent smart, it's possible?

**Comment by Magalex2x14** [comment]
Hello. The [documentation says](https://github.com/custom-components/sensor.mitemp_bt#supported-sensors): WX08ZM broadcasts switch state, tablet resource, battery level.

**Comment by Magalex2x14** [comment]
This means that as soon as the component receives the first data from this sensor, the corresponding sensor entities will be automatically created in the Home Assistant.

**Comment by pilot1981** [comment]
yes, I found this sensor but it's unavailable...

<img width="421" alt="Schermata 2020-11-05 alle 16 22 25" src="https://user-images.githubusercontent.com/46350465/98260057-25c86900-1f83-11eb-933e-244e3b7c6577.png">

**Comment by Magalex2x14** [comment]
Show your configuration.
And tell me, is there any entity from this device with a normal status (battery or switch)?

**Comment by Ernst79** [comment]
@Magalex2x14 In the code, mi_tablet is only in const.py. But CN_NAME_DICT is never used in sensor.py. 

I think this is an old entity. It is probably called mi_consumable_XXXXXXX, I guess.

**Comment by Magalex2x14** [comment]
Line 711:     setattr(sensors[cn_i], "_cn_name", CN_NAME_DICT[sensortype])

**Comment by Magalex2x14** [comment]
@Ernst79 yes, I see - the use of this attribute was lost somewhere in previous versions... The idea was that the name of the entity would correspond to the type of device.

@pilot1981 please check if there is an entity with the name given by Ernst (mi_consumable_XXXXXXX).

**Comment by Ernst79** [comment]
Hmm, why didn't find the search option that line, sometimes, I don't understand my PC......

**Comment by pilot1981** [comment]
yes, I found this one: sensor.mi_consumable_74a34ac0xxxx_2

it's works...

In your opinion in the future will be possible power on / off the Xiaomi Mosquito Repellent from HA?

**Comment by Magalex2x14** [comment]
The main idea of ​​our component is its passivity, and the implementation of a direct connection to the sensor "breaks" the operation of this component.
In the near future this will not be possible, sorry (but you are not the first to ask about this, so we keep that in mind).

**Comment by pilot1981** [comment]
ok, thanks. I close issue
