### ISSUE TITLE
No entities after reboot

### ISSUE THREAD

**Issue by star3141** [custom-components/sensor.mitemp_bt#19]
OS: Hassio in a KVM on latest Proxmox version
Hassio version: 0.103.5
Component version: 0.4.1

First of all, a slightly off topic, quick message: Thank you very much for this awesome component! I have been running it on Hassio on my Pi 3+ with an OpenMQTTGateyway for about one month without any problems.

Three days ago, I have moved from a Pi to a more powerfull Proxmox-based setup. Now I run Hassio in a KVM which works great. I have installed mitemp_bt from HACS. The OpenMQTTGateway is up and running. I can pair all of my 9 pieces of Xiaomi LYWSDCGQ without any problems and they will appear in HA. They work flawlessly until a Home Assistant reboot. Afterwards, they have disappeared from HA, although MQTT activity can be seen by using the MQTT Explorer under the topic /home/OpenMQTTGateway_ESP32_BLE/BTtoMQTT. 5 sensors are listed there. They receive temperature and humidity information. However, this information is not passed to HA, i.e., no entities are created in HA. After dis- and reconnecting the ESP32 from power and repairing the devices, everything seems to work fine, until the next Home Assistant restart. Is there some kind of debug option or log entry with further information?

**Comment by Ernst79** [comment]
The mitemp_bt component is not using mqtt and esp32, it uses Bluetooth BLE directly. So I think you have to ask somewhere else (HA forum). What is the name of the sensor you are referring to? The sensor from the mitemp_bt component start with mi_t_ and mi_h_ followed by some random letters and numbers. I think you use a mqtt sensor instead, which receives mqtt messages from your esp32 which is a different integration.

**Comment by star3141** [comment]
Yeah, sorry for bothering you because I have just figured out that I have thought that the integration worked in a different way. I came to the conclusion mentioned above because of a weird coincidence. When I have installed the temperature sensors for the first time on the Pi, I have installed your component too. Immediately after that, the sensor entities start to show up in HA so I thought that the reason for this behavior was triggered by your component. Since this worked out of the box I didn't question it. I am very sorry. The name of the sensor entities in Home Assistant are something like mitemp_# where # is some running number.

**Comment by Ernst79** [comment]
No problem. You can use both next to each other and see which one works best. 

This component (mitemp_bt) works fine, as long as the sensor is within the Bluetooth range of your machine running Home Assistant. If it is not, you have to look for other solutions. You can check the bluetooth connection by looking at the rssi attribute of the sensor. If it’s close to -85 till -100 you will probably have a too large distance between the two, which likely causes the sensor not showing up.

If the Bluetooth connection is not sufficient and you can’t move the two closer, I would recommend to use an ESP32 device and install ESPhome on it. It has support for some of the Xiaomi devices. Yours can be found here.

[Xiaomi lywsdcgq](https://esphome.io/components/sensor/xiaomi_lywsdcgq.html)

But, as explained, the mitemp_bt custom component, as is being developed here, is the only thing we can help you with here. ESPhome or ESP32 related issues should be discussed on the Home Assistant forum.Assistant forum.
