### ISSUE TITLE
Variables are overwritten with update

### ISSUE THREAD

**Issue by Ernst79** [custom-components/sensor.mitemp_bt#2]
Updating with HACS will overwrite the variables in sensor.py. These should be moved to configuration.yaml.

I will work on this coming days. 

@Magalex2x14 can you let me know what can be taken as constants and what you want in configuration.yaml? I think the limits do not have to be in configuration.yaml, am I right?

**Comment by Magalex2x14** [comment]
Yes. I think, only limits can be left as constants. Other options it would be nice to have in the configuration.yaml.

**Comment by Ernst79** [comment]
My first attempt to get the variables to the configuration failed, can't figure out why. So, I decided to start over.  

Luckily, the second attempt succeeded, I can now use configuration.yaml for the decimals option. Will add the rest tomorrow, should be easy now.
