### ISSUE TITLE
Sensors not fowarding to Homekit

### ISSUE THREAD

**Issue by leesiuu** [custom-components/sensor.mitemp_bt#20]
Hi! I’m using this component in Docker HA. I also added native HomeKit integration from HA documentation. I’m using rounded Xiaomi sensor (first one from photo). I cannot add sensors to Home (Apple) app. All sensors are not readable in app. Why it is not working?

**Comment by Magalex2x14** [comment]
I think the reason is not related to the work of this custom component.  I also use HomeKit, and everything works.

**Comment by vol4iniche** [comment]
I have the same issue, I see sensors in the HA but homekit doesn't see them.
Sensors work perfectly in the HA!!!

**Comment by leesiuu** [comment]
> I think the reason is not related to the work of this custom component. I also use HomeKit, and everything works.

Do you have LYWSDCGQ or other one in Home app on phone? Which version of HA do you have? Docker installation or other one?

**Comment by vol4iniche** [comment]
> > I think the reason is not related to the work of this custom component. I also use HomeKit, and everything works.
> 
> Do you have LYWSDCGQ or other one in Home app on phone? Which version of HA do you have? Docker installation or other one?

I use CGG1 and it works perfectly in the HA, but I have some issues on homekit :
1. I don't see my sensors in the Homekit
2. I can see the temperature sensor if I use custom templates in the HA, but not humidity
3.  humidity works only in the HA

My env:
- raspberry pi 3 B+ Buster
- Home Assistant 0.103.5 in docker

I used a mitemp_cgg1 custom module before and sensors were in the homekit, nut this module has a problem with freezes

**Comment by vol4iniche** [comment]
looks like the sensor data is correct:

last packet id: 220 
rssi: -70 
sensor type: CGG1 
battery_level: 81 
last mean of: 6 
median: 40.2 
mean: 40.2 
unit_of_measurement: % 
friendly_name:  Humidity 
device_class: humidity
--

works when I had added this to sensors.yaml:

unit_of_measurement:
- platform: template
  sensors:
     living_room_humidity:
        friendly_name: "Living Room Humidity"
        entity_id: "sensor.ID"
        device_class: humidity
        unit_of_measurement: '%'
        value_template: "{{states('sensor.ID')}}"

**Comment by leesiuu** [comment]
Works like a charm!

I think some of parameters are missing in plugin, so this is why it not works out of the box. Could author add all missing parameters or there is other problem with it? With this custom configuration entity shows in Home app on iOS!

**Comment by Magalex2x14** [comment]
OK, guys. I have no evidence under my hands that I have everything working without an additional configuration (we have holidays, and I spend them with my parents). My host is Mac mini with Debian 9, HA runs in Python virtual environment, version 0.103.4.
Let 's figure out what 's going on, and then we'll add a missing part to the code.

**Comment by leesiuu** [comment]
No problem, I will wait for your response! :)

My specs:
RPi 3B
HA 103.4 in Docker

**Comment by vol4iniche** [comment]
> OK, guys. I have no evidence under my hands that I have everything working without an additional configuration (we have holidays, and I spend them with my parents). My host is Mac mini with Debian 9, HA runs in Python virtual environment, version 0.103.4.
> Let 's figure out what 's going on, and then we'll add a missing part to the code.
Don't worries and Happy New Year:) 
All works via custom templates, so it is not a big deal.
Thanks fo your work!

**Comment by Vovoronale** [comment]
I have the same issue, so I create template sensors.

**Comment by Magalex2x14** [comment]
Guys, I can’t reproduce your problem. Here is a screenshot:
![image](https://user-images.githubusercontent.com/4982025/72280839-546b0100-364a-11ea-8144-b6019ac6a702.png)
My settings are minimal:
```yaml
homekit:
  auto_start: false
  ip_address: 192.168.98.2
```
P.S. Perhaps the point is the `auto_start` option (see above). HomeKit does not process entities that do not exist when it starts. Therefore, in addition to the disabled HomeKit autostart I have added this automation:
```yaml
- alias: Start HomeKit
  trigger:
  - platform: homeassistant
    event: start
  action:
  - delay: 00:02
  - service: homekit.start
```
The duration of the delay should be selected based on the `period` option (I have period = 60s, so I set the delay to two minutes, just in case).

**Comment by Magalex2x14** [comment]
Despite the fact that there is information about this behavior in the HomeKit documentation, I think that in addition to README it’s worth starting to start the F.A.Q. section... 
Guys, I ask for confirmation that the problem was exactly what I described above...

**Comment by leesiuu** [comment]
Yes, I have homekit autostart option set to true and this might be the problem. So I will open a ticket on homekit repo about this - maybe there can be fixed this problem.

**Comment by Ernst79** [comment]
> Despite the fact that there is information about this behavior in the HomeKit documentation, I think that in addition to README it’s worth starting to start the F.A.Q. section...
> Guys, I ask for confirmation that the problem was exactly what I described above...

I was looking at the release notes of 0.104, and it seems a general problem, which is solved in 0.104. Home Assistant will from version 0.104 restore all entities on startup as “unavailable”, if registered in the entity registry, This should fix sensors not being available in Homekit, if I understand it right. See the 
[(RC) release notes](https://rc.home-assistant.io/blog/2020/01/15/release-104/#improved-entity-handling-on-startup)

**Comment by Magalex2x14** [comment]
Good news! 👍

**Comment by Ernst79** [comment]
As stated in the release notes of home assistant 0.104, the sensor is now being restored as `unavailable` right after a restart, which should fix the HomeKit not showing the sensor. @leesiuu Can you confirm this solves your problem. 

![image](https://user-images.githubusercontent.com/24375847/72515454-37a01a80-3850-11ea-8eb8-07eeea52bfb3.png)

**Comment by leesiuu** [comment]
I will confirm it as soon I can. I need to update my HA to newest version and edit configuration. I thing, in next 3-4 days I will give you feedback if this helps.

**Comment by leesiuu** [comment]
YEAH! With new HA 0.104.0 working like a charm! I deleted template sensors and new one shows automatically!
