### ISSUE TITLE
Bluetoothctl for lescan?

### ISSUE THREAD

**Issue by xenio** [custom-components/sensor.mitemp_bt#21]
I am getting crazy to make bluetooth works on Nuc with Proxmox.
The internal bluetooth passing thru works on VM with the "bluetoothctl" command but not with "hcitool lescan".
With VM Debian and bluetoothctl scan on I get the "LYWSD02" device, hcitool lescan does not work :(

**Comment by Magalex2x14** [comment]
Hi! Excuse for a delay. Need more details about the problem - clear up what "does not work" means? Is there some error?

**Comment by Magalex2x14** [comment]
[0.5.0-alfa](https://github.com/custom-components/sensor.mitemp_bt/releases/tag/0.5.0-alfa) uses direct access to hci interface. Please, try it. Feel free to reopen issue if needed.
