### ISSUE TITLE
Any plans to support LYWSD03MMC?

### ISSUE THREAD

**Issue by francisco1977** [custom-components/sensor.mitemp_bt#22]
I've bought one Xiaomi Mijia LYWSD03MMC Smart Bluetooth 4.2 Electric Thermometer Second Generation, but as you documented, it's not supported and is not working.

Any plans to support this second generation sensor?

Thanks,
FL

**Comment by Magalex2x14** [comment]
Hard to tell.  Read closer to the end of #7 issue. Hope is there, but very small for now...

**Comment by wizel10** [comment]
If can be of help this python program reads the data from this sensor. Very reliable. 
https://github.com/JsBergbau/MiTemperature2

**Comment by capretto78** [comment]
i'd like to have a support of this sensor. What can i do to help you?

**Comment by codeclinic** [comment]
> 
> 
> If can be of help this python program reads the data from this sensor. Very reliable.
> https://github.com/JsBergbau/MiTemperature2

It looks like that could easily be used to publish the values to MQTT and then read those in HA.

**Comment by Magalex2x14** [comment]
@capretto78 problem is described [here](#7) (to avoid unnecessary reading, follow the link from the first message).

**Comment by Magalex2x14** [comment]
I changed the title of that issue and pinned it. I close this one as a #7 duplicate.
