### ISSUE TITLE
Sensor entity attributes contain spaces in name

### ISSUE THREAD

**Issue by jacekpaszkowski** [custom-components/sensor.mitemp_bt#24]
I think it is not valid that entities created by component have attributes name containing spaces: "sensor type", "last packet id", "last mean of".
It's not consistent with others, and also makes impossible to use those attributes in yaml.

**Comment by Magalex2x14** [comment]
As far as I understand, the gap in the attribute name is normal, and it is a frequent practice. There is no problem getting the value of this attribute in the template.

When an attribute contains spaces, you can retrieve it like this, for example: ``states.sensor.livingroom.attributes["Battery numeric"]``
[from here](https://www.home-assistant.io/docs/configuration/state_object/)

**Comment by jacekpaszkowski** [comment]
Please see other thread https://github.com/thomasloven/lovelace-auto-entities/issues/61
hmm, as stated in docs it is valid, you are right.
