### ISSUE TITLE
Unknown Sensor Typ

### ISSUE THREAD

**Issue by drdiablo1337** [custom-components/sensor.mitemp_bt#26]
For about a week now, the contact with the Xiaomi BT Temp sensors has stopped working after a few hours.

Restarting the RPI will solve the problem again for the next few hours. The same behavior was always with the old integrate mitemp plugin from HomeAssistant.

I don't know if that came without an update or through an update from Home Assistant, or Hassio FW itself or through the larger HACS update.

Since I installed HACS in December and used the mitemp sensor plugin from there everything has worked wonderfully.

The logs say:
Unknown sensor type: 20AAEE (the name / SN of the sensor)
"Date" custom_components / mitemp_bt / sensor.py (ERROR)

Hassio / Home Assistant runs on a Raspberry Pi 3 B

**Comment by Magalex2x14** [comment]
"Unknown sensor type" is not an error in the literal sense of the word. It only reports that a packet from an unsupported Xiaomi sensor has been received. In the current version of the component, this message has been moved to the debug level (please update component).

 From my experience, I can say that the frequent reason for stopping the acquisition of measurements is problems in the operation of the Bluetooth subsystem (hardware/drivers). I also have this (very rare) - at the same time in syslog appear bluetooth errors (timeouts and others). Reloading the kernel module helps in my case:
```shell
modprobe -r btusb
modprobe btusb
```
Raspberry uses a different module (not btusb), I can 't say exactly which... The problem has already been discussed [here](https://community.home-assistant.io/t/xiaomi-mijia-bluetooth-temperature-humidity-sensor-compatibility/43568/225?u=magalex).

**Comment by Magalex2x14** [comment]
I close it. Feel free to reopen, if help is still needed!
