### ISSUE TITLE
Can't use component if more then one usb Bluetooth controllers present

### ISSUE THREAD

**Issue by aqualx** [custom-components/sensor.mitemp_bt#27]
What is use:
 * Arch Linux x86_64
 * home assistant 0.104 on hassio
 * 2 usb bluetooth controllers

Component doesn't work at all. After logging into main docker container I can see that component starts _hcidump_, but _hcitool_ isn't started. If manually start "_hcitool -i hci0 lescan --duplicates --passive_", than hcidump start populating values from scanned ble sensors (I've added parameter "-i hci1" to hcidump call in code).

PS: Tried to append "-i hci1" to parameters @_sensor.py->start_ function with no success :(. Have no clue why it is starts OK from command line and not from python...

**Comment by Magalex2x14** [comment]
Could it be the user rights under which hcitool is running?
Please, post the output of (your paths may vary):
```shell
getcap /usr/bin/hcitool
getcap /usr/bin/hcidump
```

Please, try to
```shell
sudo setcap 'cap_net_raw,cap_net_admin+eip' `readlink -f \`which hcitool\``
```

**Comment by aqualx** [comment]
As stated previously, this is hassio (home assistant in docker based on alpine linux).
_getcap_ from **libcap** package returns nothing for both executables...

Anyway, this shouldn't be an issue as both of them started by root user:
```
bash-5.0# ps -al
PID   USER     TIME  COMMAND
    1 root      0:00 /sbin/docker-init -- /bin/entry.sh python3 -m homeassistant --config /config
    6 root      0:58 /usr/local/bin/python3 -m homeassistant --config /config
    8 root      0:00 udevd --daemon
  132 root      0:00 [hcitool]
  133 root      0:00 hcidump --raw hci
  134 root      0:00 /bin/bash
  139 root      0:00 ps -al
```
Right now only one usb controller plugged-in

**Comment by Magalex2x14** [comment]
Curious. In any case, soon I plan to release a beta component that works with the bt-interface without using external utilities. At the same time I will add an option to select an interface. Hope this solves your problem.

**Comment by Magalex2x14** [comment]
@aqualx if there is time, please check [0.5.0-alfa](https://github.com/custom-components/sensor.mitemp_bt/releases/tag/0.5.0-alfa)

**Comment by Magalex2x14** [comment]
If I understand correctly, 0.5.0 solves this problem? Feel free to reopen issue, if needed!
