### ISSUE TITLE
Cleargrass CGD1 Mijia bluetooth 5.0 support

### ISSUE THREAD

**Issue by Magalex2x14** [custom-components/sensor.mitemp_bt#38]
![image](https://user-images.githubusercontent.com/4982025/74967454-0eb00e00-542a-11ea-8f58-2b1834fd3cb0.png)

[dump.txt](https://github.com/custom-components/sensor.mitemp_bt/files/4232449/dump.txt)
According to information from the owner: "temp was aprox. around 19,5°C and the humidity about 50%".
at first glance, the messages are very similar to [LYWSD03MMC](#7) - encrypted?

**Comment by Magalex2x14** [comment]
Actually, two unknown sensors in the dump.

**54E403**
always the same message:

```
> 04 3E 21 02 01 00 00 83 BF F1 EB 49 7C 15 02 01 06 11 16 95 FE B0 54 E4 03 01 83 BF F1 EB 49 7C 0D 0E 00 A8 
> 04 3E 21 02 01 00 00 83 BF F1 EB 49 7C 15 02 01 06 11 16 95 FE B0 54 E4 03 01 83 BF F1 EB 49 7C 0D 0E 00 B5 
.
.
.
> 04 3E 21 02 01 00 00 83 BF F1 EB 49 7C 15 02 01 06 11 16 95 FE B0 54 E4 03 01 83 BF F1 EB 49 7C 0D 0E 00 AA 
> 04 3E 21 02 01 00 00 83 BF F1 EB 49 7C 15 02 01 06 11 16 95 FE B0 54 E4 03 01 83 BF F1 EB 49 7C 0D 0E 00 AB 
```

---
**587605**
Looks similarly to LYWSD03MMC
a curious difference in the length of the payload:

```
> 04 3E 29 02 01 00 00 20 EC 50 34 2D 58 1D 02 01 06 19 16 95 FE 58 58 76 05 7C 20 EC 50 34 2D 58 B4 84 AE BF 16 00 00 72 AC DB E7 DE 
> 04 3E 29 02 01 00 00 20 EC 50 34 2D 58 1D 02 01 06 19 16 95 FE 58 58 76 05 7C 20 EC 50 34 2D 58 B4 84 AE BF 16 00 00 72 AC DB E7 DE 
> 04 3E 29 02 01 00 00 20 EC 50 34 2D 58 1D 02 01 06 19 16 95 FE 58 58 76 05 7C 20 EC 50 34 2D 58 B4 84 AE BF 16 00 00 72 AC DB E7 DE 
> 04 3E 1F 02 01 00 00 20 EC 50 34 2D 58 13 02 01 06 0F 16 95 FE 30 58 76 05 7D 20 EC 50 34 2D 58 08 DE 
.
.
.
> 04 3E 1F 02 01 00 00 20 EC 50 34 2D 58 13 02 01 06 0F 16 95 FE 30 58 76 05 7D 20 EC 50 34 2D 58 08 DE 
> 04 3E 2A 02 01 00 00 20 EC 50 34 2D 58 1E 02 01 06 1A 16 95 FE 58 58 76 05 7E 20 EC 50 34 2D 58 CA 4D 40 43 C8 16 00 00 E5 D7 16 7B DE 
> 04 3E 2A 02 01 00 00 20 EC 50 34 2D 58 1E 02 01 06 1A 16 95 FE 58 58 76 05 7E 20 EC 50 34 2D 58 CA 4D 40 43 C8 16 00 00 E5 D7 16 7B DE 
> 04 3E 1F 02 01 00 00 20 EC 50 34 2D 58 13 02 01 06 0F 16 95 FE 30 58 76 05 7F 20 EC 50 34 2D 58 08 DE 
.
.
.
> 04 3E 1F 02 01 00 00 20 EC 50 34 2D 58 13 02 01 06 0F 16 95 FE 30 58 76 05 7F 20 EC 50 34 2D 58 08 DE 
> 04 3E 2A 02 01 00 00 20 EC 50 34 2D 58 1E 02 01 06 1A 16 95 FE 58 58 76 05 80 20 EC 50 34 2D 58 B8 6C 23 87 E1 16 00 00 EE 14 92 C8 DC 
> 04 3E 2A 02 01 00 00 20 EC 50 34 2D 58 1E 02 01 06 1A 16 95 FE 58 58 76 05 80 20 EC 50 34 2D 58 B8 6C 23 87 E1 16 00 00 EE 14 92 C8 DF 
> 04 3E 1F 02 01 00 00 20 EC 50 34 2D 58 13 02 01 06 0F 16 95 FE 30 58 76 05 81 20 EC 50 34 2D 58 08 DF 
.
.
.
```

**Comment by Staars** [comment]
Hi,
I just received my GCD1 and it is looking good.
While I receive the encrypted messages from above too, I also get ADV-packets with combined temp/hum-data in it.

**Comment by Staars** [comment]
![5F2D5A2D-F3F4-4269-94A1-7D2B822944D1](https://user-images.githubusercontent.com/5481060/75626304-bf56a400-5bc6-11ea-824d-f69fa322e7d2.png)

I only have my iPhone at the moment to capture data.

**Comment by Staars** [comment]
Obviously this is:

34,8 % humidity (015C)
and
23,6 °C temperature (EC).

**Comment by Magalex2x14** [comment]
Hm... This is curious.  Please, when there is an opportunity, take a full dump.  In the dump that was sent to me, I did not find any open advertisements...

**Comment by Staars** [comment]
It is in Svc-UUID: FDCD (not FE95). Bot UUID's can be received.

**Comment by Magalex2x14** [comment]
It becomes doubly curious )
```
0xFDCD - Qingping Technology (Beijing) Co., Ltd.

... 1502010611 16 CDFD 080C         20EC50342D58  0104   C400    FB01      DE
                                                 fixed?  19,6°?  50,7%?      

... 1E0201061A 16 95FE 58 587605 80 20EC50342D58  B86C2387E1160000EE1492C8 DC
```

**Comment by Magalex2x14** [comment]
Tell me, @Staars did you check for the presence of such advertisements in the case of LYWSD03MMC? 😂

**Comment by Staars** [comment]
I did not actively search for them, but with a GUI-tool (like BlueSee on the Mac) it is really hard to miss the FDCD-packets on the GCD1 by just looking at the screen for about 10 seconds. That’s why I am quite sure, that they do not exist on the LYWSD03.
Besides FDCD „is“ Quingping and not Miaomiaoce.

Side note: An active connection is cancelled after a few seconds by the CGD1, so we would need some kind of auth-procedure, but I will not intensify this sub-topic here 😁 .

**Comment by Magalex2x14** [comment]
> That’s why I am quite sure, that they do not exist on the LYWSD03.
I'm joking, of course ) Probability is near zero, yes...

**Comment by Magalex2x14** [comment]
This is an amazing observation, Christian! Interestingly, is this a bug or a feature? )
Anyway, I have a feeling that soon I will have a breakthrough in the field of encrypted messages, so for now I will not be distracted by the implementation of the Quingping message parser. Later, if I fail, then I take care of it.

**Comment by franck-outl4w** [comment]
I tried but I've an error, the token I get with modded mi home is only 24 caracters

**Comment by Magalex2x14** [comment]
you need `bind_key`, not `token`

**Comment by Magalex2x14** [comment]
or it may be called `beaconkey` - i dont know exactly, how it looks in this mod

**Comment by franck-outl4w** [comment]
It was added in his last update, gonna retry.

**Comment by franck-outl4w** [comment]
Got the bind_key, have not anymore errors but I don't see any new entity/sensor.
I read you said the alarm clock should be unpaired to mi home but I want it to work as an alarm clock first, I need Mi home (vevs edition).

**Comment by Magalex2x14** [comment]
no, no, you need to leave it paired.

**Comment by Magalex2x14** [comment]
Or what do you mean by the word "paired"? 
Clock must stay added to MiHome.
As I wrote earlier, it can update data quite rarely (from encryptors I can only compare with LYWSD03, which updates data every 10-11 minutes)

**Comment by Magalex2x14** [comment]
@Staars Have you tried the qinping-cgd1 branch?

**Comment by Staars** [comment]
> @Staars Have you tried the qinping-cgd1 branch?

I am sorry, super busy at the moment. Hopefully next week ...

**Comment by franck-outl4w** [comment]
> Or what do you mean by the word "paired"?
> Clock must stay added to MiHome.
> As I wrote earlier, it can update data quite rarely (from encryptors I can only compare with LYWSD03, which updates data every 10-11 minutes)

That's what I meaned by paired.
I missed something, what do you call qinping-cgd1 branch ?

**Comment by Magalex2x14** [comment]
@franck-outl4w never mind, I did a 0.6.2-beta pre-release
You can install it with HACS, but you need to enable "Show beta" option (through "three-dots menu" at the integration page), после чего в списке доступных версий появится 0.6.2-beta pre-release
![image](https://user-images.githubusercontent.com/4982025/76360095-678a0c80-632d-11ea-98ce-8ddd78a1a3e7.png)

**Comment by franck-outl4w** [comment]
Thank you, it works fine for me

**Comment by Magalex2x14** [comment]
Hehe! Let's wait some time to make sure everything goes well.

Tell me, did the battery information appear (sensor attribute or separate sensor entity)? 

Can you confirm that the measurement data is updated approximately once every 10 minutes, and the batteries - once an hour?

**Comment by franck-outl4w** [comment]
So far, I can only say temp and humidity first seems to update every around every3 minutes but now it's longer. I'll have more to look tomorrow.
Battery appears as attribute in both humidity and temperature sensor.

**Comment by Magalex2x14** [comment]
OK, thank you

**Comment by franck-outl4w** [comment]
Using the lovelace-ui default sensor card, I can see temperature a point every 3 minutes when it changes but when it stays stable . I don't know where I can see how often it updates.
![2020-03-11 07_58_17-Window](https://user-images.githubusercontent.com/61098268/76390896-8fe62b00-636e-11ea-8a5b-5b94286ff320.png)
![2020-03-11 07_58_48-Window](https://user-images.githubusercontent.com/61098268/76390902-92e11b80-636e-11ea-9f29-d534f66416c7.png)
![2020-03-11 07_59_07-Window](https://user-images.githubusercontent.com/61098268/76390911-95dc0c00-636e-11ea-840c-9aac77be0d2d.png)
![2020-03-11 07_59_22-Window](https://user-images.githubusercontent.com/61098268/76390918-983e6600-636e-11ea-9495-bd02eed857da.png)

**Comment by Magalex2x14** [comment]
OK, thank you!

**Comment by clau-bucur** [comment]
Guys, do we need Bluetooth 5 for this device?

**Comment by Magalex2x14** [comment]
No.

**Comment by Magalex2x14** [comment]
supported since 0.6.2
