### ISSUE TITLE
Installation on Hass.io?

### ISSUE THREAD

**Issue by jacekpaszkowski** [custom-components/sensor.mitemp_bt#4]
Hi,
very nice idea but is it possible to setup this and run on Hass.io instance?

Regards,
Jacek

**Comment by Magalex2x14** [comment]
Yes. Users write that everything works. Also [they write](https://community.home-assistant.io/t/xiaomi-mijia-bluetooth-temperature-humidity-sensor-compatibility/43568/253?u=magalex) that Installation steps 1 and 2 are not required with Hass.io. Readme will be updated.

**Comment by Ernst79** [comment]
Readme is now updated, will be visible with next release in HACS. @jacekpaszkowski can you verify that it works without step 1 and 2 on HASSio?

**Comment by jacekpaszkowski** [comment]
Wow. It work's like a charm! :) Thank You! Much more stable than standard integration.

I wonder if t would be possible to use similar approach for Mi Flora sensors?

Cheers

**Comment by Magalex2x14** [comment]
Unfortunately, as far as I was able to find out after reading several articles, polling is the only possible method of obtaining data from MiFlora. Perhaps one day I will purchase this device and study the issue myself, but it is highly likely that the previously read will simply be confirmed...

**Comment by jacekpaszkowski** [comment]
Ok, i understand.
Thank you for your support and this nice component :)

**Comment by Magalex2x14** [comment]
@jacekpaszkowski please, look at #7

**Comment by jacekpaszkowski** [comment]
@Magalex2x14 good to hear it. I can do some test but not till next week.
