### ISSUE TITLE
sensors unavailable

### ISSUE THREAD

**Issue by karkaaa** [custom-components/sensor.mitemp_bt#40]
Hello,

I have problem then install sonarr or radarr sensors. If i enable sonarr or radarr then xiaomi temperature with your repo show "unavailable". All installed from Home Assistant Community Store

Xiaomi BLE monitor sensor platform: 0.5.5
Sensor type: LYWSDCGQ
Home Assistant 0.105.5 (docker)
Sonarr: https://github.com/custom-components/sensor.sonarr_upcoming_media
Radarr: https://github.com/custom-components/sensor.radarr_upcoming_media
and this https://github.com/custom-cards/upcoming-media-card

Thank you

**Comment by Magalex2x14** [comment]
Hello, @karkaaa !

I am at a loss, because the components you mentioned do not use bluetooth and I did not find a single reason for conflict in their code.
Please tell me if there are any suspicious messages in the HA log?

**Comment by karkaaa** [comment]
No suspicious messages in the HA log. Maybe i can enable debug on sensors.mitemp_bt?

**Comment by Magalex2x14** [comment]
Yes, let's try. There is nothing else left. I, in turn, will try to install these components, and see how they will behave on my system.

**Comment by karkaaa** [comment]
it can be problem if i left empty row? 

![image](https://user-images.githubusercontent.com/34538939/75180757-868d7980-5745-11ea-91db-a599458192ba.png)

**Comment by Magalex2x14** [comment]
No, as far as I know. However, you can try to remove it 🤷‍♂️

**Comment by karkaaa** [comment]
now it is ok..
