### ISSUE TITLE
Attribute hass is None error

### ISSUE THREAD

**Issue by Ernst79** [custom-components/sensor.mitemp_bt#44]
Hi @Magalex2x14 

I now have an issue myself. After updating to 106.0/1/2 i get the following error after the restart. 

`Error during Bluetooth LE scan: Attribute hass is None for <Entity mi t_4C65A8DDB89B: 16.3>`

I'm not sure what is going on exactly. The sensor works fine.

**Comment by Magalex2x14** [comment]
I encountered the same behavior, but this only happened after the first restart right after updating to 106. I decided that the unavailability of entities attributes was related to the processes associated with autoupgrading some HA components... In subsequent restarts, the system behaved normally.

**Comment by Ernst79** [comment]
I had it after each update, so also right after updating to 0.106.1 and to 0.106.2. 

Normal restarting does not give the error, I agree. 

It’s not affecting the behavior, all just works normal. But it’s strange that we now get this error. We could wait for the next 0.107 release to see if this behavior will stay. I will also have a look through the release notes to see if something has changed in Home Assistant that could have caused this.

**Comment by Ernst79** [comment]
I looked through the release notes, but can’t find a change that looks related. Let’s wait for 0.107 to see if it solves automatically.

**Comment by Ernst79** [comment]
I have to correct myself, I do have this error also after a normal restart.

**Comment by Magalex2x14** [comment]
Yes, I also have some entities updated only after the third `period` since the restart...

**Comment by WhoSayIn** [comment]
I have the same issue. It goes away after a few restarts. Started to happen after upgrading Hassio to 0.106

**Comment by Magalex2x14** [comment]
As I understand it, additional reboots are not required. The error indicates a certain “unavailability” of the entity at the time of updating. By the next update(s), with this entity everything is OK.

**Comment by WhoSayIn** [comment]
ah, good to know! thanks. I'll wait next time this happens and see if the sensor data comes back.

**Comment by Magalex2x14** [comment]
Note: error occurs during `entity_to_update.async_schedule_update_ha_state()`

**Comment by Magalex2x14** [comment]
I don’t know why the asynchronous callback was used, as the main thread of our component is synchronous... Fix will be included in the next release.

**Comment by Magalex2x14** [comment]
Version 0.6.0 published.
