### ISSUE TITLE
Not pulling data from Veg Trung Sensor. 

### ISSUE THREAD

**Issue by Diondelpino** [custom-components/sensor.mitemp_bt#54]
This component works great for my veg trung sensors with Mac addresses starting with 80:EA:CA:88... however one of my sensors has a MAC address starting with C4:7C:8D:67... and for some reason this integration doesn’t make a sensor for it. Also this integration doesn’t seem to be able to pull battery %, like the MiFlora component can. Tried both configuration options.

**Comment by Magalex2x14** [comment]
As pointed in the README.md, these sensors does not broadcasts battery status. Unfortunately.

To solve the problem with C4:7C:8D:67... sensor, try to enable the `report_unknown` option first (use this instruction from FAQ - "[My sensor from the Xiaomi ecosystem is not in the list of supported ones. How to request implementation?](https://github.com/custom-components/sensor.mitemp_bt/blob/master/faq.md#my-sensor-from-the-xiaomi-ecosystem-is-not-in-the-list-of-supported-ones-how-to-request-implementation)"), and see if corresponding messages appear in the log.

**Comment by Diondelpino** [comment]
So I enabled the report_unkown option but all that appears in the log is this. “ 2020-03-12 11:14:39 INFO (SyncWorker_3) [custom_components.mitemp_bt.sensor] Attention! Option report_unknown is enabled, be ready for a huge output...” but there isn’t any data that follows.

**Comment by Magalex2x14** [comment]
It looks like there are no messages from this sensor at all. In a normal situation, this can happen when the sensor is too far away or when it does not send messages at all.

Have you tried placing the sensor closer to the HA-host?

Is this sensor added to the official app? Most sensors do not send messages unless they "paired". They also do not send messages while connecting to them (it may be another component or script).

For a complete picture, I need a full dump of everything that comes to the bt-interface. This can be done using the btmon tool:

```shell
sudo btmon -t -w btmon.log
```

After running the command, wait 15 minutes and abort it using CTRL+C.

**Comment by Magalex2x14** [comment]
In addition to activating the sensor in the official application, you should also check for firmware updates - I don’t know how things are with VegTrug devices, but MiFlora with early firmware [does not send messages at all.](https://github.com/esphome/issues/issues/260#issuecomment-487684720)

**Comment by Diondelpino** [comment]
Ahhh that’s what it was. It was running old firmware v2.7.0. Couldn’t use the veg trung app. But using the flower care app and switching the region to Mainland China got it updated. And now the data is coming through. Thanks for the help mate.
