### ISSUE TITLE
Rounded value does not return decimal place

### ISSUE THREAD

**Issue by borpin** [custom-components/sensor.mitemp_bt#56]
The returned value does not always get returned in the same format.

With decimal places as "1", a value that rounds to 20.0 will just be returned as 20.

**Comment by Magalex2x14** [comment]
The component is not guilty of missing the decimal place (even if not significant) :)
The fact is that the component uses the standard built-in function `round()` for rounding, which returns a float anyway, if the rounded number was a float (and this is always true for temperature and humidity):

![image](https://user-images.githubusercontent.com/4982025/77043900-7e84ca80-69cf-11ea-9052-ff170b79baa2.png)

![image](https://user-images.githubusercontent.com/4982025/77043862-6f058180-69cf-11ea-8eaa-0b624bea3ade.png)

How did you identify the behavior you described? And why is this important to you?

**Comment by borpin** [comment]
I was seeing it on an MQTT feed out of HA. Possibly something else causing it.

I just like constant formatting and it showed up as 20 in a dashboard.

I'll close this and dig a bit further. Cheers.
