### ISSUE TITLE
No module named 'aioblescan'

### ISSUE THREAD

**Issue by lukas-musalek** [custom-components/sensor.mitemp_bt#59]
I tried to configure my new LYWSD03MMC thermomenters, so I upgraded mitemp_bt to last version, but my already working thermometer LYWSDCGQ stop working also (no devices listed in sensors).
If I put back my previous version of mitemp_bt, it is working again.

So I tried to upgrade hassio. I upgraded to:
arch | armv7l
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.19.106-v7
python_version | 3.7.7
timezone | Europe/Prague
version | 0.107.7
virtualenv | false

But now, when I try to check configuration, I'm getting error:
**Platform error sensor.mitemp_bt - No module named 'aioblescan'**

Thanks for help.

Lukas

**Comment by lukas-musalek** [comment]
Weird, after couple of restarts, configuration seem to be valid now and also LYWSD03MMC thermomenetrs seems to be working now....I didn't changed anything...

**Comment by Ernst79** [comment]
Could be that the custom component was not loaded properly. You need to properly shut down HA, and start it afterwards manually. This will unload the old (build-in) component and load the new custom component. A restart of your RPi will do the same. After that, LYWSD03MMC needs some time to get the first measurements, as it is sending the measurements not very often.

**Comment by Magalex2x14** [comment]
I close. Reopen if needed.
