### ISSUE TITLE
Xiaomi Honeywell Formaldehyde Monitor (JQJCY01YM) support

### ISSUE THREAD

**Issue by Chao-chao00** [custom-components/sensor.mitemp_bt#60]
Hello, i am new to Home Assistant and Github.
Is it possible to integrate the "Xiaomi Honeywell Formaldehyde Monitor (JQJCY01YM)" into the sensor.mitemp_bt custom components ?

This sensor has a square shape and displays Formaldehyde (HCHO) level in mg/m^3 on the screen. It is powered by 2 AAA batteries and connects to Mi Home app with Bluetooth 4.2. I think it only works on the Mi Home Mainland China server and in the app it displays HCHO level, temperature and humidity.

Here are the specs :
https://www.priceboon.com/product/xiaomi-honeywell-jqjcy01ym/

Did:		blt.3.129cmt93c5s00
Name:		Xiaomi Honeywell Formaldehyde Monitor
Model:		yuemee.airmonitor.mhfd1
Token:		d8d033653b181975ac23d8e2
Mac:		48:57:43:00:9E:13

I checked the parings.txt file created by the "vevs Mi Home app" and it might use encryption like the LYWSD03MMC. The Bindkey is 24 characters long.

I followed the instructions on enabling logger and report_unknown option in Home Assistant and here is my home-assistant.log file attached to this message. I can confirm using the "nRF Connect" Android app that the device that appears in the log with MAC address : 485743009E13 is indeed the JQJCY01YM sensor.
[home-assistant.log](https://github.com/custom-components/sensor.mitemp_bt/files/4426301/home-assistant.log)

**Comment by Magalex2x14** [comment]
It seems that the data is not encrypted. So far I have not looked in great detail, but at first glance, there are no potential problems with the implementation of support for this sensor.
A little later I will look in more detail. I will let you know.

**Comment by Magalex2x14** [comment]
OK. In the data you provided, I see everything: temperature, humidity, battery and formaldehyde (id 0x1010). The formaldehyde values ​​obtained from your data are 9 and 7.
As I understand it, this number should be divided by 100 - so we get 0.09 and 0.07 mg/m3. I ask you to confirm that these are approximately the readings that were displayed on the device during the recording of the log.

I think that this weekend I will do everything and we will test it with you.

**Comment by Chao-chao00** [comment]
> The formaldehyde values ​​obtained fro

> The formaldehyde values ​​obtained from your data are 9 and 7.
> As I understand it, this number should be divided by 100 - so we get 0.09 and 0.07 mg/m3

Yes you are correct, the HCHO value displayed on the screen were 0.09 and 0.07 mg/m3.

**Comment by Magalex2x14** [comment]
@Chao-chao00 I pushed [0.6.4-beta](https://github.com/custom-components/sensor.mitemp_bt/releases/tag/0.6.4-beta) with support for your sensor.

Please check if everything is fine.

Also please note that since the sensor measures in small numbers, 3 decimal places are forced for formaldehyde if rounding is enabled (the sensor sends quite a lot of messages, and there is an opportunity to slightly increase the resolution).

**Comment by Magalex2x14** [comment]
[You can install beta with HACS](https://github.com/custom-components/sensor.mitemp_bt/issues/38#issuecomment-597322412)

**Comment by Chao-chao00** [comment]
Ok i followed your instructions and now i have the latest beta version installed "Installed: 0.6.4-beta".
Then i checked my entities in Home Assistant to see if a new one appears for the Formaldehyde Sensor but nothing.
Then i noticed that all my entities (i have 4 BLE temp sensor) from the mitemp_bt integration have a red exclamation mark in the status field, and they are all unavailable from the Lovelace entity card.
![mitemp_bt entities problem](https://user-images.githubusercontent.com/31290198/78534779-31995480-7815-11ea-95d7-161eabc708a7.png)

So i decided to enable debug logging by adding to the configuration.yaml file this :

logger:
  default: warn
  logs:
    custom_components.mitemp_bt: debug
As mentioned in this link : 
https://github.com/custom-components/sensor.mitemp_bt/blob/master/faq.md#my-sensor-from-the-xiaomi-ecosystem-is-not-in-the-list-of-supported-ones-how-to-request-implementation

And there is this error (see the attached log file) :

  File "/config/custom_components/mitemp_bt/sensor.py", line 172, in parse_xiaomi_value
    (fmdh,) = FMDH_STRUCT.unpack(hexvalue)
struct.error: unpack requires a buffer of 4 bytes

[home-assistant (debug).log](https://github.com/custom-components/sensor.mitemp_bt/files/4436700/home-assistant.debug.log)

**Comment by Magalex2x14** [comment]
Oh. Sorry, my fault... I pushed the bugfix. Please, reinstall 0.6.4-beta.

**Comment by Chao-chao00** [comment]
> Oh. Sorry, my fault... I pushed the bugfix. Please, reinstall 0.6.4-beta.

Ok no problem. Thanks for answering quickly, i reinstalled 0.6.4-beta and it seems to work fine. My 4 previous BLE temp sensors work and i have 4 new entities (temp, humidity, battery and formaldehyde) related to the Xiaomi Honeywell Formaldehyde Monitor.

![Xiaomi Honeywell Formaldehyde Monitor](https://user-images.githubusercontent.com/31290198/78540847-f3a12e00-781e-11ea-855d-d5bfeea2dbe3.png)

I will wait a bit to plot a history graph and see what is message received frequency.

**Comment by Chao-chao00** [comment]
![Xiaomi Honeywell Formaldehyde Monitor (graph)](https://user-images.githubusercontent.com/31290198/78559131-09721b80-783e-11ea-9e9e-a9c5741cf0b1.png)

Above you can see the Temperature for the 1st, Battery Level and Humidity for the 2nd, and Formaldehyde for the 3rd graph. From what i can see, with the default "period: 60" Home Assistant updates the sensor every 60s (even though the Formaldehyde Monitor sends many times a minute) which works as expected.

Thank you @Magalex2x14 for your work on this integration, for now it seems to work and i will keep an eye and tell you if it doesn't work anymore after an update for example.

Note : if a value is constant for many minutes, we can't really see that Home Assistant updates the sensor every 60s. I simulated a change of formaldehyde on the device to have changing numbers and that's why there is a spike on the graph.

**Comment by Magalex2x14** [comment]
Yes, the built-in history card is not very suitable for this. Personally, I solved this issue with the help of InfluxDB and Grafana - this gives much more opportunities for data analysis.
Thank you for a competent approach.
And please show what the details of the formaldehyde sensor look like (by clicking on the sensor entity or in the states table on the HA developer tab).

**Comment by Magalex2x14** [comment]
What confuses me is that you only show two decimal places, although I forced 3 in the code for this type of sensors. How do you configure the `decimals` option?

**Comment by Chao-chao00** [comment]
> What confuses me is that you only show two decimal places, although I forced 3 in the code for this type of sensors. How do you configure the `decimals` option?

I haven't configure the "decimals" option anywhere so it should be the default 3 according to what you said for the Formaldehyde Monitor. Maybe for example the value 0.08mg/m3 is considered 3 decimals because there are 3 digits, even though technically it is 2 decimals.

**Comment by Chao-chao00** [comment]
Nevermind, i found some values that have 3 decimals. Since this device only has a resolution of 0.01mg/m3 and that the formaldehyde value doesn't change a lot (seems like some kind of smoothing in the data processed by the device itself) when i check it on the device screen, in a span of 60s it is likely that Home Assistant will receive the same Formaldehyde value so it will display only a 2 decimal value.

But sometimes in the span of 60s if Home Assistant receives different Formaldehyde values, then it will average them and probably have a 3 decimals averaged value.

![3 decimals](https://user-images.githubusercontent.com/31290198/78562707-fe21ee80-7843-11ea-8af1-4e12da12d6d6.png)
![3 decimals (2)](https://user-images.githubusercontent.com/31290198/78562713-01b57580-7844-11ea-9b0f-6304793c49eb.png)

**Comment by Magalex2x14** [comment]
Ha! Thank you!
Yes, the component averages all the values ​​obtained over the period. This allows to slightly increase the resolution of the sensor (nicer graphics, etc).

**Comment by Magalex2x14** [comment]
I think that with the code regarding formaldehyde sensor, everything is fine.
I think that next weekend if everything is really going well, I will release 0.6.4.

**Comment by Chao-chao00** [comment]
Ok if there is a problem i will tell you. If i don't say anything, that means that everything is working fine.

**Comment by Magalex2x14** [comment]
Closed with 0.6.4 release.

**Comment by Magalex2x14** [comment]
@Chao-chao00 hi, can you try version 0.6.6-beta? You're the only one I know with a formaldehyde sensor.
How to install beta using HACS I described [here](https://github.com/custom-components/sensor.mitemp_bt/issues/64#issuecomment-616194292).

**Comment by Chao-chao00** [comment]
Hi @Magalex2x14  i updated to the 0.6-6-beta version half an hour ago and the folmaldehyde sensor seems to work fine because i am still receiving the data at the same rate, i don't see anything wrong.
I will notify you if i notice any problem.

**Comment by Chao-chao00** [comment]
@Magalex2x14 Hello, i noticed a weird behavior of the JQJCY01YM and i think it is due to the fact that you forced 3 decimals for this sensor for better accuracy even thought the sensor only reports 2 decimals. From what i can see it makes the chart less readable, let me explain.

The sensor seems to alternate between 2 or 3 values (like 0.01 0.02 and 0.03) when at idle and stays at one of the values a couple of minutes and then changes value. I think this is due to how the sensor works internally and how the Formaldehyde measurement is made.

With 2 decimals we should have a clean square wave type of curve. But with the 3rd decimal added, when it transitions from let's say 0.02 to 0.03, an intermediate value like 0.028 will appear once at the transition due to the fact that Home Assistant averages values each 60s (Configuration Variable "period").

![formaldehyde 3 decimals problem (1)](https://user-images.githubusercontent.com/31290198/82139573-e0887180-9852-11ea-8b1b-af1ff6b3dbb2.png)
![formaldehyde 3 decimals problem (2)](https://user-images.githubusercontent.com/31290198/82139664-ca2ee580-9853-11ea-954c-9d8a5f13b4e2.png)

So the curve has intermediate values and sometimes spikes that makes it less readable. 
I think we should remove the 3rd decimal and stick with only 2 decimals. What do you think ?

**Comment by Magalex2x14** [comment]
To judge the existence of a problem, you need to look at the actual amount of data received for the period. If there are few of them (say, less than 5), then there is no particular sense in increasing the number of digits, yes.

In this case, I can only rely on your experience, and if you think that there is no sense in three decimal places, then let's leave two.
Before making changes to the component’s public code, you can manually find the line with the text `fdec = 3` and replace it with` fdec = 2` (there is only one such place in the code). Later I will include this change in some of the releases.
