### ISSUE TITLE
Xiaomi BT Sensor doesn't work after update

### ISSUE THREAD

**Issue by Norec39** [custom-components/sensor.mitemp_bt#66]
Hello i've just update my homeassistant to 0.108.8 and it show an error message 
The following integrations and platforms could not be set up:
- sensor.mitemp_bt
Please check your config.

Here is my config :
sensor:
  - platform: mitemp_bt
    rounding: True
    decimals: 2
    period: 60
    log_spikes: False
    use_median: False
    hcitool_active: False

**Comment by Magalex2x14** [comment]
Just upgraded to 0.108.8 on both of my systems (Debian 9 Python venv and Hassio HassOS 3.13) without any problems.

Try to stop and start HA. Or reboot your system.

**Comment by Norec39** [comment]
I try both multiple times and it doesn’t work..

**Comment by Norec39** [comment]
Should I update my Debian ?

**Comment by Magalex2x14** [comment]
Not if everything worked before the HA update.
Did you do a configuration check?
![image](https://user-images.githubusercontent.com/4982025/80007175-94a21100-84ce-11ea-91ea-aa343ca04a20.png)

**Comment by Magalex2x14** [comment]
Did you try to reinstall component?

**Comment by Norec39** [comment]
Yeah, it’s due to the hcitool_active param which no longer exist
Thank you !

**Comment by Magalex2x14** [comment]
Oh, yes, I also did not pay attention immediately )
