### ISSUE TITLE
Support for Xiaomi Mijia Mosquito Repellent Smart Version (Model WX08ZM)

### ISSUE THREAD

**Issue by pplucky** [custom-components/sensor.mitemp_bt#70]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/16407309/80510555-cc97d100-8972-11ea-81b8-2166e87feab7.png">

**Specifications**:
Brand: Xiaomi Mijia
Model: WX08ZM
Rated: Voltage 3V
Rated: Power 0.06W
Wireless Connections: Bluetooth 4.2 BLE
Battery: Powered by 2 x AA batteries
CMIIT: 2019DP1690

[Link to product](https://www.gearbest.com/home-smart-improvements/pp_3001071306331967.html)

Device is added to Mi Home and advertised via BLE (checked via ESP32 BLE tracker in esphome), as:
Found device MASKED RSSI=-57
   Address Type: PUBLIC
   Name: 'MJ_MR_V1' 

I imagine controlling the device is not a possibility (or setting schedules), but at least some information is accessible from Mi Home and would be useful to obtain:
Battery level: 20%
Tablet remaining: 95%
Estimated service life: 85 days

HA Log [https://pastebin.com/embed_js/Tghiqze1](https://pastebin.com/embed_js/Tghiqze1)

Also found this [github](https://github.com/ioBroker/ioBroker.docs/blob/master/docs/en/adapterref/iobroker.ble/README.md) where it seems some info is already being fetched from these devices. 

Mac address identified as MASKED, but it is clearly visible.

Please let me know if there's anything else I can prove helpful with to try to support this device.

Thanks in advance.

**Comment by Magalex2x14** [comment]
OK, I see the following data:

```
1695fe  50300a04  63  3407b54aa374  1210 01 00 dc - switch  0
1695fe  50300a04  64  3407b54aa374  0a10 01 1b de - battery 27
1695fe  50300a04  67  3407b54aa374  1210 01 01 e1 - switch  1
1695fe  50300a04  69  3407b54aa374  0a10 01 14 e0 - battery 20
```

I do not yet know what to do with the implementation of the switch state - I need to think about it.

The battery is easy to add.

I do not see data on the tablet resource.
It is likely that this data is not transmitted at all in broadcast messages, but it’s worth trying to collect a log for a longer period (it’s probably worth turning device on for this time so that the tablet’s resource changes, and at this time you shouldn't connect using the application because then the sensor can stop broadcasting).

**Comment by Magalex2x14** [comment]
About the situation with the switch: the problem is similar to that indicated in # 68.
Theoretically, I can implement support for a binary sensor, but due to the periodic nature of the component's operation, data on the state of such a sensor will arrive with some delay, and round-trip operations within the same period will not be visible at all.
The only way out of this situation, I see a complete alteration of the component to asynchronous mode and continuous processing of incoming messages on the fly, which leads to the need to solve new problems related to the fact that many sensors send messages quite often. In general, it is pretty laborious...

**Comment by pplucky** [comment]
> OK, I see the following data:
> 
> ```
> 1695fe  50300a04  63  3407b54aa374  1210 01 00 dc - switch  0
> 1695fe  50300a04  64  3407b54aa374  0a10 01 1b de - battery 27
> 1695fe  50300a04  67  3407b54aa374  1210 01 01 e1 - switch  1
> 1695fe  50300a04  69  3407b54aa374  0a10 01 14 e0 - battery 20
> ```
> 
> The battery is easy to add.

Cool, and I suppose the switch status (0 = Off / 1 = On) would also be - even if not controlable.

> I do not see data on the tablet resource.
> It is likely that this data is not transmitted at all in broadcast messages, but it’s worth trying to collect a log for a longer period (it’s probably worth turning device on for this time so that the tablet’s resource changes, and at this time you shouldn't connect using the application because then the sensor can stop broadcasting).

I can try that later, but if that would imply having the % change, it may take a lot of time and having HA generate these info logs like crazy can be an issue for me. I need to use my test system for this.

> About the situation with the switch: the problem is similar to that indicated in #68.

I had already read about it also, and it makes sense.

> Theoretically, I can implement support for a binary sensor, but due to the periodic nature of the component's operation, data on the state of such a sensor will arrive with some delay, and round-trip operations within the same period will not be visible at all.

In the context of this device, it would still be useful to know if it is on/off, even though it is not possible to change it with this component. In the context of this specific device, it is not something that you turn on and turn off after 5 minutes (like it may happen for a light). You tend to have it turned on/off for large periods of time.

> The only way out of this situation, I see a complete alteration of the component to asynchronous mode and continuous processing of incoming messages on the fly, which leads to the need to solve new problems related to the fact that many sensors send messages quite often. In general, it is pretty laborious...

I can only imagine, but honestly for this specific device, it's not worth the hassle.

**Comment by Magalex2x14** [comment]
I will wait for additional data from you (if any) because if I implement support for this sensor partially, it will be difficult to obtain additional data, since it will no longer be unknown, and messages from it will no longer be written to the log.

**Comment by pplucky** [comment]
> I will wait for additional data from you (if any) because if I implement support for this sensor partially, it will be difficult to obtain additional data, since it will no longer be unknown, and messages from it will no longer be written to the log.

Following your approach of looking at data, I think I managed to find it myself, using 2 different devices I have (which currently have different tablet % reported in Mi Home):

1695fe  50300a04  ff    a1a2b64aa374  1310 01 4b c6 - TABLET 75 (%)
1695fe  50300a04  66  3407b54aa374  1310 01 5f  e6 - TABLET 95 (%)

Here is the [full log](https://pastebin.com/embed_js/psr5C6Xk), for you to check for yourself.
Here is a [Google Sheet](https://docs.google.com/spreadsheets/d/1okLY7Y8nwqBTXDLr4SOMZDDoj3rGjR-64psz6Z7LgAo/edit?usp=sharing) with my formulas to obtain the above information (as well to confirm the one you provided before).

**Comment by Magalex2x14** [comment]
Excellent work, thank you! This weekend I will try to prepare a beta that you can try.

**Comment by pplucky** [comment]
> Excellent work, thank you! This weekend I will try to prepare a beta that you can try.

Thanks a lot.

I need to check if I can somehow adapt this to esphome, for usage with an ESP32 instead (due to BT connectivity it's not easy to have everything in range for the HA device where your custom component is running).

**Comment by Magalex2x14** [comment]
@pplucky I need your help.
I just pushed the necessary changes to the [`whitelist`](https://github.com/custom-components/sensor.mitemp_bt/tree/whitelist) branch. Please replace the contents of your installed sensor.py and const.py files with files from this branch (`custom_components/mitemp_bt` folder).

In my opinion, everything should work, but I'm not yet ready to push a public beta - there are too many structural changes. Please try, and if everything goes well, then I will make a public beta and after a while, I will publish the release. I will prepare the documentation for now.

**Comment by pplucky** [comment]
> @pplucky I need your help.
> I just pushed the necessary changes to the [`whitelist`](https://github.com/custom-components/sensor.mitemp_bt/tree/whitelist) branch. Please replace the contents of your installed sensor.py and const.py files with files from this branch (`custom_components/mitemp_bt` folder).
> 
> In my opinion, everything should work, but I'm not yet ready to push a public beta - there are too many structural changes. Please try, and if everything goes well, then I will make a public beta and after a while, I will publish the release. I will prepare the documentation for now.

Looks fine:
<img width="927" alt="image" src="https://user-images.githubusercontent.com/16407309/80848263-98d6d880-8c0a-11ea-884f-06871041aca3.png">

**Comment by Magalex2x14** [comment]
These are exactly the entities from my component, have you confused them with ESPHome entities? )

custom.mitemp_bt creates entities that begin with `mi_`
In addition, I would like to take a look at how the switch will look in Lovelace.

**Comment by pplucky** [comment]
> These are exactly the entities from my component, have you confused them with ESPHome entities? )

My bad, sorry. Corrected now, check above.

**Comment by Magalex2x14** [comment]
Thank you very much! Let me know if something goes wrong or if ideas come up.

**Comment by Magalex2x14** [comment]
> What do you mean by switch? My idea would be to probably use a template switch to represent the device status...

Did not notice your question. Since this is a new kind of entity in my component, I wanted to make sure that all its properties and methods are set correctly, and it looks normal in Lovelace. Or are you asking what it is at all? The state of this switch corresponds to what the sensor sends, and this entity is a two-state HA binary sensor that can be used in automation and templates.

**Comment by Magalex2x14** [comment]
0.6.8 with WX08ZM [released](https://github.com/custom-components/sensor.mitemp_bt/releases/tag/0.6.8)

**Comment by Arturmdr** [comment]
I have a mini PC Intel Celeron J4115 and Home Assistant in docker.
I put WX08ZM in discovery mode and use the command:

$ bluetoothctl
[bluetooth]# scan on
Discovery started
[NEW] Device xx:xx:xx:xx:xx:xx MJ_MR_V1

It find MJ_MR_V1 that is my WX08ZM.

My config in Home Assistant:
sensor:
  - platform: mitemp_bt

But can't pair, my log is:
2020-11-04 22:10:08 DEBUG (SyncWorker_13) [custom_components.mitemp_bt.sensor] update_ble called
2020-11-04 22:10:08 DEBUG (SyncWorker_13) [custom_components.mitemp_bt.sensor] Discovering Bluetooth LE devices
2020-11-04 22:10:08 DEBUG (SyncWorker_13) [custom_components.mitemp_bt.sensor] Time to analyze...
2020-11-04 22:10:08 DEBUG (SyncWorker_13) [custom_components.mitemp_bt.sensor] Getting data from HCIdump thread
2020-11-04 22:10:08 DEBUG (SyncWorker_13) [custom_components.mitemp_bt.sensor] HCIdump thread: joining
2020-11-04 22:10:08 DEBUG (Thread-34) [custom_components.mitemp_bt.sensor] HCIdump thread: main event_loop stopped, finishing
2020-11-04 22:10:08 DEBUG (Thread-34) [custom_components.mitemp_bt.sensor] HCIdump thread: Run finished
2020-11-04 22:10:08 DEBUG (SyncWorker_13) [custom_components.mitemp_bt.sensor] HCIdump thread: joined
2020-11-04 22:10:08 DEBUG (SyncWorker_13) [custom_components.mitemp_bt.sensor] Spawning HCIdump thread(s).
2020-11-04 22:10:08 DEBUG (SyncWorker_13) [custom_components.mitemp_bt.sensor] HCIdump thread: Init
2020-11-04 22:10:08 DEBUG (SyncWorker_13) [custom_components.mitemp_bt.sensor] HCIdump thread: Init finished
2020-11-04 22:10:08 DEBUG (SyncWorker_13) [custom_components.mitemp_bt.sensor] Starting HCIdump thread for hci0
2020-11-04 22:10:08 DEBUG (Thread-36) [custom_components.mitemp_bt.sensor] HCIdump thread: Run
2020-11-04 22:10:08 DEBUG (SyncWorker_13) [custom_components.mitemp_bt.sensor] HCIdump threads count = 1
2020-11-04 22:10:08 DEBUG (Thread-36) [custom_components.mitemp_bt.sensor] HCIdump thread: Connection
2020-11-04 22:10:08 DEBUG (Thread-36) [custom_components.mitemp_bt.sensor] HCIdump thread: Connected
2020-11-04 22:10:08 DEBUG (Thread-36) [custom_components.mitemp_bt.sensor] HCIdump thread: start main event_loop
2020-11-04 22:10:08 DEBUG (SyncWorker_13) [custom_components.mitemp_bt.sensor] Finished. Parsed: 3 hci events, 0 xiaomi devices.

How can I make this work?

**Comment by Magalex2x14** [comment]
@Arturmdr next time please open a separate issue for your question.
Our component does not require pairing with a device - it is passive. For the device you are connecting to start sending data packets, it must be activated (just added) in the official MiHome application.
You do not need to perform any additional actions (except for configuring the whitelist option, if you use it).

**Comment by Arturmdr** [comment]
Magalex2x14, thank you for the answer, but i can't make it work.

I try all:
- bluetoothctl scan on / scan off
- Device connected to MiHome and disconnected
- With whitelist and without. 
- With all setting and only with "sensor:  platform: mitemp_bt"
- etc

Always have "DEBUG (SyncWorker_14) [custom_components.mitemp_bt.sensor] Finished. Parsed: 3 hci events, 0 xiaomi devices."

**Comment by Magalex2x14** [comment]
Just to clarify - the device must be added to MiHome, and not removed from there. You can close the application, but do not remove the device from it.

Do you use any other services or components that use bluetooth?

Do you know what type of bluetooth module is installed in your system? Try [this fork](https://github.com/custom-components/sensor.mitemp_bt/issues/61#issuecomment-624306036) of our repository that solves problems with some bt-adapters (used in the Intel NUC platform, perhaps this is also your case).

Are you using the official HassOS image? What version? 4.14 has known bluetooth issues, you need to update to 4.15.

**Comment by Arturmdr** [comment]
Thank you Magalex2x14, with the fork work, but it is too slow identify the state
I only have  sensor.mi_sw_xxx and sensor.mi_tablet_xxx. Is that ok?
Is there any way to turn it on and off in Home Assistant?
Thank you again

**Comment by Magalex2x14** [comment]
Yes, the list of the entities you have is correct (there may be an entity for the battery if you have enabled such an option).

No, our component does not have the ability to control devices. If you need to control, then at the moment I do not know of any other solution, except for the use of a Xiaomi gateway and [this component](https://github.com/AlexxIT/XiaomiGateway3) (I can not say anything about its stability and operating features).

Due to the periodic nature of the component's operation, the sensor status updates come at the end of the window described by the period option (this is normal for measuring sensors). If the switching sensor status has changed in this window and restored to the previous one, these events will not be recorded. Work is underway to implement real-time updates for switching sensors.

**Comment by Arturmdr** [comment]
Thank you Magalex2x14, all cleared up now...
