### ISSUE TITLE
Sensor doesnt work after agt-get update

### ISSUE THREAD

**Issue by IvSan** [custom-components/sensor.mitemp_bt#72]
I executed full system update on my raspberry:
`sudo apt-get update && sudo apt-get upgrade`
Previously all was fine. But after update my mitemp_bt sensor in HA stopped working. 
I have no idea what to start checking with.
Has someone meet same issue?

**Comment by Magalex2x14** [comment]
@IvSan Did you find the cause of the problem (if it was at all)?

**Comment by IvSan** [comment]
Nope, just reinstalled rasbian from scratch and run fresh docker HA container. It works in my case.
