### ISSUE TITLE
Real-time processing of the BLE Advertisements

### ISSUE THREAD

**Issue by Magalex2x14** [custom-components/sensor.mitemp_bt#76]
Since there were requests for the implementation of support for "switching" sensors (binary sensors like switches, the presence or motion sensors), I began to think about redesigning the platform for processing messages from sensors in real-time.
The lack of the current approach (periodic) I have already described in [this](https://github.com/custom-components/sensor.mitemp_bt/releases/tag/0.6.8) release note:

*Due to the fact that this component has a periodic nature of the operation, the state of the binary sensor will arrive with some delay. For example, if your period option is one minute (by default this is the case), and the state of the sensor has changed by 30 seconds of the period, then the state of the binary sensor entity in HA will change only after the remaining 30 seconds have passed.*

Theoretically, we just need to transfer the parser code to the thread that receives messages from the interface ("HCIdump" thread). However, it is necessary to solve several problems arising in this case:
- many sensors send quite a lot of messages, which leads to the issue of the minimum sufficient performance (the current approach eliminates this problem due to the fact that the collection of messages and their processing can occur "simultaneously" due to multithreading);
- if the entity is updated for each received message, this will lead to a monstrous load on the storage system (database), therefore, it is necessary to provide the logic of accumulation and averaging of the readings of the measuring sensors;
- since the component allows you to collect data from several interfaces, there is a problem of unjustified additional load due to the fact that often messages from all interfaces will be the same (it is necessary to transfer the duplicates processing logic to the earliest possible stage); 

I am pleased to hear comments on this issue from all interested.
Is there any real reason to do this?

-----
ToDo:
- ~~check whether any event filtering is implemented at the protocol level;~~
- try to receive hci events in the HA event_loop, leave the processing in the component thread;
- try both to receive data and to process it in the HA event_loop;
- compare the load on the system:
   - parsing messages immediately upon receipt;
   - parsing messages in the updater loop;
   - upon receipt, only filter, do the rest in the updater loop;

**Comment by Magalex2x14** [comment]
@Ernst79 what do you think about this issue?

**Comment by Ernst79** [comment]
I think, if you decide to change things, you should make a clear distinction between sensors and switches. Switches should react immediately. Sensors do not, and the period can already been set by the user. Binary sensors are the only exception, and kind of depend on the device they represent. 

I could imagine that you make it  an option for binary sensors and switches, such that the user can choose wether he/she wants immediate response (with the warning of huge data flows if you do that for a sensor that sends data very often) or that he want to use it the normal/old way (which should be the default).

Which device(s) are you thinking of, that would need immediate response type of behavior?

**Comment by Magalex2x14** [comment]
We already have two devices in our requests: this is a repellent and a lamp with a motion sensor (there is no dump for it yet). I do not know such devices anymore (I have not studied the assortment). The Mija BLE standard also implies these types of binary objects: a leakage sensor, a door/window opening sensor, a gas sensor, a smoke sensor, and so on, I don’t remember exactly already.
Yes, there is no urgent need for such changes yet, but I want to be prepared for this )
Well, there is some "sporting" interest also ) I’ll experiment for now...

**Comment by Magalex2x14** [comment]
I created a new branch, realtime_tests, in which I will gradually move towards processing messages in real-time, as they arrive. At the moment, the BLE ADV parser is completely transferred to the HCIdump thread. While I do not see noticeable changes in the load on the system (rpi3b+, one bt-interface, 9 sensors, 5 of them with encryption). I’m watching further.

**Comment by Magalex2x14** [comment]
It seems that the realtime code is working fine. In any case, I do not see any problems so far. It was even possible to reduce the CPU load to about the level of a "periodic" code.
The only thing I do not have the opportunity to test the operation of binary sensors.
I’ll observe a week, and I will offer this code to try the owners of sensors with switches.
Branch **realtime_tests**, if anyone is interested.

**Comment by Magalex2x14** [comment]
I recently posted a [0.7.0-beta](https://github.com/custom-components/sensor.mitemp_bt/releases/tag/0.7.0-beta) that implements real-time processing.
I do not see any problems with it, it works well for me. I’ll wait a little longer, and will merge it to the master branch.

The next step is to attempt to make component completely async without using additional threads (I try to follow [component quality](https://developers.home-assistant.io/docs/integration_quality_scale_index/) ladder)
