### ISSUE TITLE
The modle of LYWSD03MMC have deffrent token

### ISSUE THREAD

**Issue by ai-xcode** [custom-components/sensor.mitemp_bt#77]
I have got the token of LYWSD03MMC, but the token is deffent as usual. It's like "779F30FC4AD3EFEA121CE56E", but I have the token of other devices is same as usual with the same way.In the Xiaomi online store, the device is marked as model 2, So I wonder if Xiaomi may have modified his encryption method in the new version. When I use this new token to configure the encryptors parameter, I get an error.

**Comment by Magalex2x14** [comment]
You should not take a `token` (24 characters), but a key that has a length of 32 characters. Depending on the receiving method, it may be referred to as `bind_key` or `beaconkey`. I draw your attention to the fact that the `token` is always present in LYWSD03MMC pairing requests, but this is not what you need - look for `bind_key` or `beaconey`.

If you really were dealing with a new model, then it would be called differently (not LYWSD03MMC).

**Comment by ai-xcode** [comment]
Thank you very much, I have used the sniffing method to get the new key, and I can get the data new. I use LYWSD02 and LYWSD03MMC. Thank you very much for your work. ps. The easiest way to get the key is to use stream sniffing. Select "Group By Host" from the stream APP sniffing record, select "api.io.mi.com" Host, find "POST https://api.io.mi.com/app/device/bltbind", select "Request"-"Preview Form"-"Fomat"-"Decode", you can see the bind_key you need. If you cannot find the above content in the results of sniffing, it is recommended to re-trust and re-sniff the CA certificate. You can refer to @ntin5002 Operation. https://community.home-assistant.io/t/xiaomi-passive-ble-monitor-sensor-platform/177352/117.Very detailed and simple.
Have a good day!

**Comment by Magalex2x14** [comment]
A link to the mentioned instruction post is included in the FAQ.
