### ISSUE TITLE
Unable to get data from 3 sensors

### ISSUE THREAD

**Issue by jopie282** [custom-components/sensor.mitemp_bt#82]
Hi,

I have been unable to add multiple sensors since the last mitemp update.
Are there more people with the same problem?

**Comment by Magalex2x14** [comment]
Hello!

This component works with a large number of sensors without any problems.
Personally, I get data from nine sensors (various types) using it.
Need more details.
Have you added at least one sensor?
What type of sensors?
Is there anything suspicious in the log?

**Comment by Ernst79** [comment]
Closing this issue, as no response is given by topic starter. Feel free to reopen the issue if the issue isn’t solved yet.
