### ISSUE TITLE
Temperature sensor LYWSD03MMC won't work HA 0.112  

### ISSUE THREAD

**Issue by antoweb** [custom-components/sensor.mitemp_bt#89]
After last today update 0.112 of hassio, temperature and humidity still to unknown value.
Sensor Xiaomi model LYWSD03MMC

**Comment by pgsylvestre** [comment]
Temperature Sensor works after some boot ups and Humidity Sensor does not work at all for me 'Non-numeric' after upgrade to 0.112

**Comment by Ernst79** [comment]
Most likely related to #88

**Comment by stefangries** [comment]
Same for me:

```
2020-07-01 22:38:27 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mitemp_bt/sensor.py", line 775, in update_ble
    discover_ble_devices(config, aeskeys, whitelist)
  File "/config/custom_components/mitemp_bt/sensor.py", line 692, in discover_ble_devices
    sensors[h_i], mac, config, hum_m_data[mac], stype[mac]
  File "/config/custom_components/mitemp_bt/sensor.py", line 499, in calc_update_state
    entity_to_update.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 416, in schedule_update_ha_state
    assert self.hass is not None
AssertionError
```

Also getting a lot of there errors in the host log:

`Bluetooth: hci1: Frame reassembly failed (-84)`

**Comment by cretzu8523** [comment]
Same problem

Logger: homeassistant.core
Source: helpers/entity.py:416
First occurred: 11:07:05 (1 occurrences)
Last logged: 11:07:05
Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mitemp_bt/sensor.py", line 775, in update_ble
    discover_ble_devices(config, aeskeys, whitelist)
  File "/config/custom_components/mitemp_bt/sensor.py", line 699, in discover_ble_devices
    sensors[m_i], mac, config, moist_m_data[mac]
  File "/config/custom_components/mitemp_bt/sensor.py", line 499, in calc_update_state
    entity_to_update.schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 416, in schedule_update_ha_state
    assert self.hass is not None
AssertionError

**Comment by hudzikj** [comment]
Try last beta version. My LYWSDCGQ and VegTrug Grow Care Garden works after upgrade to HA 0.112 and upgrade component to 0.7.1-beta

**Comment by cagnulein** [comment]
i confirm, 0.7.1-beta works with LYWSD03MMC  too

**Comment by antoweb** [comment]
Yes but I'm using HACS and I prefer wait stable versione otherwise I have to switch out from have and back in

**Comment by hudzikj** [comment]
HACS supports beta version of this component. Just switch the slider.

**Comment by antoweb** [comment]
Oh thanks good to know

**Comment by Magalex2x14** [comment]
Hello!  Unfortunately, I will not be able to take a close look at this problem, as I am on a business trip, and I will not have access to my system for several more days (maybe a week).  Glad the latest beta is working.  There are a lot of serious changes in it - let's hope that there are no other problems ...

**Comment by antoweb** [comment]
> HACS supports beta version of this component. Just switch the slider.

Hello,
I don't know how to switch the slider. Can you help me?

**Comment by rudizl** [comment]
> > HACS supports beta version of this component. Just switch the slider.
> 
> Hello,
> I don't know how to switch the slider. Can you help me?

Three dots, Reinstall, switch the slider and wait a few seconds. The module will show, that there is an update.

**Comment by antoweb** [comment]
> > > HACS supports beta version of this component. Just switch the slider.
> > 
> > 
> > Hello,
> > I don't know how to switch the slider. Can you help me?
> 
> Three dots, Reinstall, switch the slider and wait a few seconds. The module will show, that there is an update.

Thank you very much

**Comment by cretzu8523** [comment]
> i confirm, 0.7.1-beta works with LYWSD03MMC too

not working for me

**Comment by antoweb** [comment]
> i confirm, 0.7.1-beta works with LYWSD03MMC too

I confirm working for me too

**Comment by cagnulein** [comment]
> > i confirm, 0.7.1-beta works with LYWSD03MMC too
> 
> not working for me

did you restart HASS after the upgrade?

**Comment by cretzu8523** [comment]
> > > i confirm, 0.7.1-beta works with LYWSD03MMC too
> > 
> > 
> > not working for me
> 
> did you restart HASS after the upgrade?

yes

**Comment by stefangries** [comment]
For me, 0.7.1-beta is working with LYWSD03MMC.

**Comment by cretzu8523** [comment]
before to update the component i updated the sensor on mihome app, i think that is my problem

**Comment by ronron261** [comment]
The LYWSD02 doesn 't work with the beta

**Comment by antoweb** [comment]
> before to update the component i updated the sensor on mihome app, i think that is my problem

So now you have firmware 109? Can anyone confirm that this component doesn't work with new sensor firmware?

**Comment by antoweb** [comment]
> For me, 0.7.1-beta is working with LYWSD03MMC.

Hello, can you plz tell me which version firmware you have?

**Comment by cretzu8523** [comment]
> > before to update the component i updated the sensor on mihome app, i think that is my problem
> 
> So now you have firmware 109? Can anyone confirm that this component doesn't work with new sensor firmware?

Yes 109

**Comment by blackscreener** [comment]
Only one LYWSD03MMC is working for me.

**Comment by konnectedvn** [comment]
> i confirm, 0.7.1-beta works with LYWSD03MMC too

Can't install it using HACS.

**Comment by orrpan** [comment]
> Only one LYWSD03MMC is working for me.

I got 2/3 working

**Comment by antoweb** [comment]
> > i confirm, 0.7.1-beta works with LYWSD03MMC too
> 
> Can't install it using HACS.
Yes you can, reinstall switching the slide to show beta

**Comment by orrpan** [comment]
0.112.1 also?

**Comment by konnectedvn** [comment]
> > > i confirm, 0.7.1-beta works with LYWSD03MMC too
> > 
> > 
> > Can't install it using HACS.
> > Yes you can, reinstall switching the slide to show beta

Finally I can. HACS ui issue. Thanks!
Confirm 0.7.1-beta works. I have 3 LYWSD03MMCs.

**Comment by antoweb** [comment]
> > > > i confirm, 0.7.1-beta works with LYWSD03MMC too
> > > 
> > > 
> > > Can't install it using HACS.
> > > Yes you can, reinstall switching the slide to show beta
> 
> Finally I can. HACS ui issue. Thanks!
> Confirm 0.7.1-beta works. I have 3 LYWSD03MMCs.

Glad to know you did it. Can you confirm which firmware version you have for yours LYWSD03MMCs and Wich hassio 0.112 or 0.112.1?

**Comment by antoweb** [comment]
> 0.112.1 also?

Work for me component 0.71 beta and hassio 0.112.1 but i can confirm if work with last 109 version of sensor firmware

**Comment by hugosbnarciso** [comment]
Hello,

with me 0.7.1-beta worked for a while and then stopped working

**Comment by PTR-W** [comment]
> Hello,
> 
> with me 0.7.1-beta worked for a while and then stopped working

Same behavior for me with beta 0.7.1
Firmware: 1.0.1_0068

**Comment by antoweb** [comment]
> > Hello,
> > with me 0.7.1-beta worked for a while and then stopped working
> 
> Same behavior for me with beta 0.7.1
> Firmware: 1.0.1_0068

Work for me 0.71beta hassio 0.112.1 device firmware 0106

**Comment by TychoWerner** [comment]
I have been **unable** to get it working with:
- Home Assistant version 0.112.1 running on Raspberry Pi 3B+
- Firmware on the device: 1.0.0_0106, hardware version B1.4
- Acquired keys with Android vevs mod version 5.6.100
- HACS 1.1.2, mitemp_bt 0.7.1-beta

Currently going to update Home Assistant to 0.112.2 and update the firmware on the device to 1.0.0_0109

**Comment by TychoWerner** [comment]
> > Hello,
> > with me 0.7.1-beta worked for a while and then stopped working
> 
> Same behavior for me with beta 0.7.1
> Firmware: 1.0.1_0068

How have you been able to get the firmware to 1.0.1_0068, for me the latest is 1.0.0_0109
I tried updating with iPad Air 2, Xiaomi Home v4.32.0, China Mainland server, iOS 13.5.1

**Comment by PTR-W** [comment]
> How have you been able to get the firmware to 1.0.1_0068, for me the latest is 1.0.0_0109
> I tried updating with iPad Air 2, Xiaomi Home v4.32.0, China Mainland server, iOS 13.5.1

I'm using the european server (in my case germany). Maybe that's why.

**Comment by TychoWerner** [comment]
> > How have you been able to get the firmware to 1.0.1_0068, for me the latest is 1.0.0_0109
> > I tried updating with iPad Air 2, Xiaomi Home v4.32.0, China Mainland server, iOS 13.5.1
> 
> I'm using the european server (in my case germany). Maybe that's why.

I switched to Germany for the server but I still don't get the update, are you on iOS or Android?

**Comment by PTR-W** [comment]
> I switched to Germany for the server but I still don't get the update, are you on iOS or Android?

Android. But I just figured out that I'm talking about the hygrometers (definitely different firmware, sorry for confusion). But every BLE Sensor from Xiaomi (my miflora sensors too) seems to have this issue now.

**Comment by bbostock** [comment]
I am running the custom component on Home Assistant 112.4 and I get the Future Exception error. 
Where can I  find 0.7.1-beta please?

**Comment by Ernst79** [comment]
Pres the three dots on the integration card in hacs, reinstall and then move the slider to show beta’s.

**Comment by bbostock** [comment]
Thanks for the quick reply. I may be being very stupid, but  on Home Assistant OS I can't find an integration card for Xiaomi Mijia BLE Temperature and Humidity Sensors, it's built-in as mitemp_bt.

**Comment by Ernst79** [comment]
Are you sure you have installed the custom component via HACS. This will "overrull" the built-in component in Home Assistant. Go to HACS --> Integrations --> + --> look for Xiaomi passive BLE monitor sensor platform. Carefully follow the instructions under "How to install", as you might have to do more than just installing it via HACS (depending on your home assistant installation).

**Comment by antoweb** [comment]
> I am running the custom component on Home Assistant 112.4 and I get the Future Exception error.
> Where can I find 0.7.1-beta please?

If using HACS remove e reinstall selecting show beta

**Comment by antoweb** [comment]
> I am running the custom component on Home Assistant 112.4 and I get the Future Exception error.
> Where can I find 0.7.1-beta please?

but the new version non-beta works also

**Comment by bbostock** [comment]
I'm not using HACS. I'm running HassOS on RPi so mitemp_bt is builtin. This version doesn't recognise the LYWSD03MMC. I copied the custom component which does, but it gets the Future Exception error. 

I am also using ESPHome BLEHub, which now works after enabling the beta version.

Because the way my house is laid out, I have a BLEHub for sensors in the bedrooms, and use the RPI for sensors near my office.They configuration has been very reliable for my older Mijia sensors.

**Comment by bbostock** [comment]
Pleased to say after understanding what HACS is, getting it installed and running all my LYWSD03MMC sensors are working! Both on mitemp_bt & ESPHome Beta. Sorry to have really missed the point in my earlier comments. Great development work by those involved.

**Comment by Ernst79** [comment]
Closing this issue,feel free to reopen if this issue still exists.
