### ISSUE TITLE
problem of LYWSD03MMC

### ISSUE THREAD

**Issue by Zy143L** [custom-components/sensor.mitemp_bt#90]
use "Mi Home" APP Cracked version
LYWSD03MMC Token is "3b5bce273e8a24f50d586853"
Only 24 , not 32
Info:
Model: miaomiaoce.sensor_ht.t2
Token: 3b5bce273e8a24f50d586853
<mitemp_bt> is unavailable

**Comment by TychoWerner** [comment]
My currently working setup:
Home Assistant running on RPI 3B+
Got my Keybind from the Android app v5.6.100; made my file structure with /vevs/logs in the external SD card
Updated the LYWSD's to firmware 0109; this made the change for me
