### ISSUE TITLE
Performance with HHCCJCY01 very bad in HA 112.2

### ISSUE THREAD

**Issue by ACrazyConcept** [custom-components/sensor.mitemp_bt#91]
So I have a few HHCCJCY01 and a couple of GCLS002. And after HA 112.2 I get so spotty sensor updates. Some of them never come at all.

This is after 10 hours with 0.7.1 beta: 
![image](https://user-images.githubusercontent.com/36438756/86529153-a03a8c80-beae-11ea-92c1-7f6e0c668a95.png)

**Comment by tonyawad88** [comment]
I have a similar issue, where the MiFlora BLE sensor transmits data / works for a few hours and then all of a sudden no data reported for a long period of time as highlighted in the img below. Running on a Pi which isn't moved at all during this period nor the sensor is moved. I am also running 0.7.1 beta. 

@ACrazyConcept are you getting a similar graph as below / 'spotty' results? 

Authors, I can contribute as well if you guide me a bit to the source of the problem. 
Thank you!

![Screen Shot 2020-07-21 at 4 42 58 PM](https://user-images.githubusercontent.com/3638322/88105089-5f5e9b00-cb71-11ea-93fd-6771928fcddd.png)

**Comment by ACrazyConcept** [comment]
The issue seems to be resolved for me with HA 113.1 and mitemp_bt 0.6.10

**Comment by Ernst79** [comment]
Thanks, I will close the issue. Problems with the beta version will be investigated further, as there are more problems. These can be discussed in #98
