### ISSUE TITLE
New sensor mho-c201 with E-INK request support

### ISSUE THREAD

**Issue by shirou93** [custom-components/sensor.mitemp_bt#92]
Hi,

this sensor is not supported yet?

https://www.aliexpress.com/item/32854817316.html?spm=a2g0o.productlist.0.0.172c55efOZZveB&algo_pvid

mho-c201 E-INK sensor.

**Comment by Ernst79** [comment]
For instructions to add new devices to the component, please follow the procedure described [here](https://github.com/custom-components/sensor.mitemp_bt/blob/master/faq.md#my-sensor-from-the-xiaomi-ecosystem-is-not-in-the-list-of-supported-ones-how-to-request-implementation). Please report back the requested information, such that we can add the device.

**Comment by znanev** [comment]
This sensor doesn't have Bluetooth connectivity. It is a nice standalone sensor - I own a couple of these, but for Home Assistant integration you'll have to look up some of the Bluetooth enabled sensors like CGG1, LYWSD02 and the likes.

**Comment by znanev** [comment]
@shirou93 MHO-C201 is a "dumb" sensor, but there is now a Bluetooth-enabled version of it: MHO-C401:

https://www.aliexpress.com/item/4001174769598.html

I've just created a pull request, which adds support for the "smart" version of this sensor: #106

**Comment by Ernst79** [comment]
support for MHO-C401 is added in 0.6.11
