### ISSUE TITLE
Don't work with latest Hassio

### ISSUE THREAD

**Issue by pristis** [custom-components/sensor.mitemp_bt#96]
Hello!

Еverything worked fine until the update to HassOS 4.11/Supervisor 228. Now I see this error message on logs and the system doesn't work with my Xiaomi sensor anymore. I am using also latest sensor.py from this repo committed on July 10 .

`Invalid config for [sensor.mitemp_bt]: [rounding] is an invalid option for [sensor.mitemp_bt]. Check: sensor.mitemp_bt->rounding. (See /config/configuration.yaml, line 58). Please check the docs at https://www.home-assistant.io/integrations/mitemp_bt`

There is my config:
```
platform: mitemp_bt
    rounding: True
    decimals: 2
    period: 60
    log_spikes: False
    use_median: False
    active_scan: False
    batt_entities: False
    report_unknown: False
```

I will appreciate some help. Thanks!

**Comment by Ernst79** [comment]
Isn’t this an issue with too many spaces in your config before rounding and the other options. Not sure, but could you check this. My config looks like this (in a sensor.yaml file).
```
# Mitemp bluetooth
- platform: mitemp_bt
  rounding: True
  decimals: 2
  period: 60
  log_spikes: True
  use_median: False
  batt_entities: False
```

**Comment by Ernst79** [comment]
Oh, it looks like home assistant is using the built-in component. The error message is referring to the official home assistant website. Most likely, the custom component is not installed correctly. Please install it again, preferably via HACS.

**Comment by Ernst79** [comment]
Could you let us know if this solves your issue?

**Comment by pristis** [comment]
> Could you let us know if this solves your issue?

Hello!

Thank you for your reply and sorry for my late answer, I was away.

I just deleted `/custom_components/mitemp_bt` and try with original stock configuration. And it works.

After that, I downloaded the custom files from the repo, put them again on the hassio and followed the installation steps (about shut down/restart etc). The error is the same. The strange thing is that configuration worked perfectly from december until the last update. And something goes wrong. 

Now I can't even restart Hassio normally, because of "Config error. See the logs for details." notification. You know the error already.

This is my sensor part of my configuration.yaml. And again to say, this configuration worked half a year without any problems and after the last update my RF Receiver also stops working, not only mitemp_bt custom component.

[My party configuration.yaml on pastebin](https://pastebin.com/rJUmRpcf)

**Comment by Ernst79** [comment]
Could you try the following. First, only have the following in you configuration (of mitemp_bt)

`  - platform: mitemp_bt`

So, leave all options out. Next Restart HA. If that succeeds add the options you need/want and restart again.

**Comment by pristis** [comment]
Meanwhile I made update to latest HassOS 4.11 / Home Assistant 0.113.1 / Supervisor v. 229  and everything works again. I don't know what was the problem with the previous version.

Thanks for your time!

**Comment by Ernst79** [comment]
Great, thanks for the feedback.
